### ISSUE TITLE
Binary non-passive change between 1.1.1 and 1.2.0

### ISSUE THREAD

**Issue by bokken** [raphw/byte-buddy#100]
A library built against bytebuddy 1.1.1 fails if executed with bytebuddy 1.2.0 with following error:

```
Exception in thread "main" java.lang.NoSuchMethodError: net.bytebuddy.dynamic.DynamicType$Builder$MethodDefinition$ImplementationDefinition.intercept(Lnet/bytebuddy/implementation/Implementation;)Lnet/bytebuddy/dynamic/DynamicType$Builder$MethodDefinition;
	at com.cerner.mmf.interceptors.util.GenericProxyFactory.createGenericProxyConstructor(GenericProxyFactory.java:157)
```

Where the GenericProxyFactory code being referenced is:

```
        builder = builder.implement(Proxy.class)
                         .method(ElementMatchers.any())
                         .intercept(MethodDelegation.to(ProxyClassImpl.class)
```

It appears that the DynamicType$Builder$MethodDefinition$ImplementationDefinition.intercept method has changed from returning a MethodDefinition to returning a ReceiverTypeDefinition. This is not binary compatible, as it changes the method signature.

As an aside, you could consider using the [clirr-maven-plugin](http://www.mojohaus.org/clirr-maven-plugin/) to detect/report compatibility changes.

**Comment by raphw** [comment]
You are right. The update introduced a source-compatible but a binary-imcompatible change. It was necessary to incorporate receiver types into the API.

i can say that this was the last missing feature such that API incomible changes will not happen anymore until Java 9 comes out.

**Comment by bokken** [comment]
Can any/all future incompatible changes (whether binary or source) result in major version changes?

**Comment by CodingFabian** [comment]
In my opinion the nature of bytebuddy does not allow it for the semver treatment you might be used to in libraries. I also think ASM does not stick to semver. like when they fixed the stack frame issue with java 8, that was not a major releases, but you could argue it should have been.

as pointed out in the documentation, you ALWAYS should repackage bytebuddy. By doing so you automatically take care about binary compatibility, as you would-recompile your "dependency" when upgrading.

I would also vote for not forcing any source compatibility. @raphw is doing a fantastic job fixing esotheric edge cases. Sometimes that requires a dramatic change.

By forcing clirr compatibility (btw, clirr is broken right now for java 8, because bcel is broken, because cglib is broken, because.. maybe somebody should do a bytecode lib...) one usually slows down the progress because required changes cannot be made.

I am a heavy user of ByteBuddy since 0.5, and I upgraded on every release. I had never a problem with the amount of incompatible changes I needed to follow.
I know that this might not apply to everybody, but most people are happy that there is an active bytecode manipulation library which is not yet dead. lets try to keep it that way.

**Comment by raphw** [comment]
I cannot promise it but I can say that I will honestly attempt to avoid API changes in the future and that I announce them if they happen. There will not be any API changes for bug fix releases.

**Comment by raphw** [comment]
To be fair: Byte Buddy is intended to be usable without repackaging as long as the `byte-buddy` artifact is used rather than `byte-buddy-dep`. In the `0.*` versions, I still considered Byte Buddy a beta version and applied some major renamings and API refactorings. 

I am trying to keep Byte Buddy stable from now on. Since version 1.2, Byte Buddy supports receiver type annotations and therewith all features that Java 8 currently offers. Due to the increasing download numbers I understand that changing the API too much will lead to incompatibilities and this is not in the library's interest. I can however not promise to not make changes outside of major version releases as the byte code format itself - other than Java - is not backwards-compatible and Byte Buddy being an API for manipulating byte code needs to evolve with the API. As long as the changes are small, I will from now on rather announce API-breaking changes in the release notes and I will not apply them form bug-fix versions.

Thank you all for your input, I appreciate it!
