### ISSUE TITLE
How to set an Advice return value in Kotlin

### ISSUE THREAD

**Issue by pimterry** [raphw/byte-buddy#1014]
I'm trying to use bytebuddy from within Kotlin, and I'm having trouble with the Advice API. Specifically this:

```java
import net.bytebuddy.asm.Advice;

public class MyAdvice {
    @Advice.OnMethodExit
    public static void myMethod(@Advice.Return(readOnly = false) String returnValue) {
        returnValue = "hello world";
    }
}
```

That's the standard way to set a return value in Java, as I understand it?

The Kotlin equivalent doesn't compile:

```kotlin
object MyAdvice {
    @Advice.OnMethodExit
    @JvmStatic
    fun myMethod(@Advice.Return(readOnly = false) returnValue: String) {
		returnValue = "hello world"
    }
}
```

This works perfectly for other Advice logic, but not for setting a return value, because parameters are always immutable in Kotlin, [by design](https://blog.jetbrains.com/kotlin/2013/02/kotlin-m5-1/).

Is there any other way to set the method return value in an Advice class? If not, would you be open to adding a mechanism like that? A `ReturnValue` parameter so you could call `returnValue.set(value)` would work well imo, and would also avoid IDE warnings about variables that are assigned to but never read.

Right now, my whole codebase is in Kotlin, except my advice classes which all have to be implemented separately in Java. It's not an impossible problem, but it is annoying! :smiley:

**Comment by raphw** [comment]
The issue with your suggestion is that the byte code in the advice method would no longer map to what is rendered in the adviced method. The reason advice works so well is because it is directly mappable to the byte code that needs generation and can be adjusted in a single pass, i.e. Byte Buddy processes the advice method's byte code as it is received and weaves it into the target method while that method's byte code is also streamed. If the single assignment to the return value's store is changed to a method call, one would need to trace that object if it suddendly got passed around as in `Object other = returnValue` which has no real representation. Therefore, this is unfortunately not possible. It's too bad Kotlin does not allow any opt-out of parameter immutability. Generally, it is however a good idea to write advice in Java for other reasons, too, for example for stack map frame consistency, despite it being annoying.

**Comment by raphw** [comment]
I'm closing this issue, please get in touch if you have any further questions.

**Comment by shacha086** [comment]
Given the constraint of direct bytecode mapping, would using a mutable holder (such as a single-element array or wrapper object) for the return value be fundamentally incompatible as well, or has this approach been considered before?

**Comment by raphw** [comment]
This is tricky to change, as the method signature can be preprocessed without entering the byte code. Any change to that would be a severe performance issue, so this is why I normally suggest to write the advices in Java. They can call out to Kotlin from a reachable helper.
