### ISSUE TITLE
Enabling lambda instrumentation breaks class initialization for Log4j2 PropertiesUtil

### ISSUE THREAD

**Issue by rdicroce** [raphw/byte-buddy#1024]
Here's a [reproducer project](https://github.com/raphw/byte-buddy/files/6158454/bb-bug.zip). Merely enabling lambda instrumentation, without actually applying any transformations, is enough to cause this error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.apache.logging.log4j.util.PropertiesUtil
	at org.apache.logging.log4j.status.StatusLogger.<clinit>(StatusLogger.java:78)
	at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:61)
	at com.sg.throwaway.ByteBuddyMain.main(ByteBuddyMain.java:18)
```

I looked at the source code for PropertiesUtil and it does contain some lambdas, so my guess is that ByteBuddy is having a problem with those lambdas. I tried adding Listener.StreamWriting.toSystemOut() but that didn't print any information at all.

**Comment by raphw** [comment]
I would recommend against using the strategy. Lambdas are too baked into the JVM nowadays and it's close to impossible to support any corner case. If you add `-Dnet.bytebuddy.dump=/some/folder`, you can even see the lambdas that are created, I assume there's a race somewhere.

It works on 8, not on 11, I will look into it some time but likely the loading mechanism has changed somewhat. Likely it's because of lambdas in JVM core classes.

**Comment by raphw** [comment]
This is captured in https://github.com/raphw/byte-buddy/issues/1066
