### ISSUE TITLE
[Question] Can disabling type validations become an issue?

### ISSUE THREAD

**Issue by LikeTheSalad** [raphw/byte-buddy#1074]
Hi!

Someone [has recently had issues](https://github.com/LikeTheSalad/android-buddy/issues/4) with some "Java-illegal" code done by the Kotlin compiler while using `android-buddy`, and apparently, this is something that has already come up before in an issue created for Byte Buddy: https://github.com/raphw/byte-buddy/issues/764 - Where it seems like the solution is to disable the type validations.

As you know, a lot of projects in Android make use of Kotlin, which is why I was thinking that maybe it's good to just disable the type validations in Android Buddy for good for everybody. I'm ok with doing so, but I just wanted to confirm with you first if you think that disabling this validation could cause some issues in the future? I'm asking because I guess there's a reason for Byte Buddy to have this validation enabled by default, so I'm a bit weary that by disabling it for good might bring some issues later, but if that's not the case, I think it'd be nice disabling it to avoid issues with Kotlin.

Thanks!
Cesar

**Comment by raphw** [comment]
Hi, the validation issue is really something that only affects Android. The Java compiler will not normally allow you to use a language feature when compiling class files to a byte code level where this feature is not supported. With Android however, the build chain will allow you to use for example Java 8 features and then downgrade the class file version in the build chain.

I agree with you however that if targeting Android, disabling type validation makes a lot of sense since Android does not follow the default conventions for what a valid Java class is.

**Comment by LikeTheSalad** [comment]
Many thanks for your quick response! - It makes sense to disable this validation in Android then, I'll make those changes.

Thanks again.
