### ISSUE TITLE
ByteBuddyAgent fails to install with trivial SecurityManager

### ISSUE THREAD

**Issue by pburka** [raphw/byte-buddy#1103]
Using bytebuddy-agent 1.11.13, the agent fails to install if a trivial no-op SecurityManager is installed. I ran into this when I tried to upgrade a custom JUnit harness that installs a SecurityManager to block `System.exit()` during unit tests.

### Test case
```
import java.security.Permission;
import net.bytebuddy.agent.ByteBuddyAgent;

public class BB {
    private static class NoOpManager extends SecurityManager {
        NoOpManager() { }

        @Override
        public void checkPermission(Permission perm) { }

        @Override
        public void checkPermission(Permission perm, Object context) { }
    }
    
    public static void main(String[] args) throws Throwable {
        System.setSecurityManager(new NoOpManager());
        var instr = ByteBuddyAgent.install();
        System.out.println(instr);
    }
}
```

On Java 11.0.9, this prints `null` with bytebuddy 1.11.13, instead of the expected `sun.instrument.InstrumentationImpl@66a3ffec`. The test works as expected on 1.11.3.

**Comment by raphw** [comment]
Indeed, if the security manager is package private, the privilege check currently fails due to the change to reflection (as a reaction to deprecating the security manager altogether). Byte Buddy must resolve the `checkPermission` method on the `java.util.SecurityManager` type directly, not the potential (package-private) subclass. This is now fixed on master.
