### ISSUE TITLE
ClassInjector$UsingReflection is relying on `sun.misc.Unsafe` to work

### ISSUE THREAD

**Issue by brunojcm** [raphw/byte-buddy#1109]
I'm trying to make https://github.com/open-telemetry/opentelemetry-java-instrumentation work without the `jdk.unsupported` module and I bumped into a few issues that I think are being caused by `byte-buddy`.

The common stacktrace accross the different issues is:
```
java.lang.UnsupportedOperationException: Cannot get defined package using reflection: sun.misc.Unsafe
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.getDefinedPackage(ClassInjector.java:470)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:246)
```

I expect `ClassInjector$UsingUnsafe` to crash with such an error if `jdk.unsupported` is not present, but not `ClassInjector$UsingReflection`. Is this correct?

The original issues with full stacktraces are:
https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/4096
https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/4100

**Comment by raphw** [comment]
It's because of OpenTelementry [relying on sun.misc.Unsafe](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/38470bd2e64bd59266020d4aca5dfb60f0d027c1/muzzle/src/main/java/io/opentelemetry/javaagent/tooling/HelperInjector.java#L247) by choice, this will stop working eventually.

Since Java 8, the recommended approach is using a `MethodHandle.Lookup` which [Byte Buddy also offers](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/dynamic/loading/ClassInjector.java#L1513).

If Java 8 and later should be supported, even without Unsafe, one would check the current version and create an injector accordingly.

**Comment by brunojcm** [comment]
> It's because of OpenTelementry [relying on sun.misc.Unsafe](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/38470bd2e64bd59266020d4aca5dfb60f0d027c1/muzzle/src/main/java/io/opentelemetry/javaagent/tooling/HelperInjector.java#L247) by choice, this will stop working eventually.

it is checking if it's supported, isn't it?
https://github.com/open-telemetry/opentelemetry-java-instrumentation/commit/38470bd2e64bd59266020d4aca5dfb60f0d027c1

The line you linked is using `UsingReflection`,  not `UsingUnsafe`. So is the stack trace I quoted.

> Since Java 8, the recommended approach is using a `MethodHandle.Lookup` which [Byte Buddy also offers](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/dynamic/loading/ClassInjector.java#L1513).

I'll have a look into that. 

> If Java 8 and later should be supported, even without Unsafe, one would check the current version and create an injector accordingly.

**Comment by raphw** [comment]
In newer Java version, injection using reflection [also requires unsafe for bootstrapping reasons](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/dynamic/loading/ClassInjector.java#L513). It is therefore [required to check it's availability](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/dynamic/loading/ClassInjector.java#L295). 

What you would do normally is to check if the `java.lang.Module` type is present and use `ClassInjector.UsingLookup` then and `ClassInjector.UsingReflection` otherwise. In the latter case one should technically check if the mechanism is available as some special VMs do not allow for it even on 8.
