### ISSUE TITLE
How to match high version and low version

### ISSUE THREAD

**Issue by cor0ps** [raphw/byte-buddy#1141]
when  i  load   my bytebuddy 1.11.22 high version   to  my  springboot  ,  but   I   found  my  springboot had   low  version    asm   
and  bytebuddy， so  i  can  not  javaagent  my  high  bytebuddy  version   and   now   I  solve  this  problem  is   delete  low  version   but  in   product   environment  I   can   not  also  delete  low  version jar。

So   How  Can  I    solve  this problem ?

**Comment by raphw** [comment]
If you are booting the application yourself, you can simply put the right version on the class path, the agent will just be added there anyways.

Another alternative is to use a trampoline agent where you attach your agent to an isolated class loader upon startup, for example by creating a URLClassLoader to which you attach your jars, instead of loading your jars as part of the actual agent. You would then for example add your agent jar as a resource to the actual agent which you then load within the trampoline.

Third, you can shade Byte Buddy into a different namespace. There are plugins for Maven and Gradle.
