### ISSUE TITLE
Access FieldValue of Base class

### ISSUE THREAD

**Issue by amar1019** [raphw/byte-buddy#1155]
Hi,
I have injected a public field in parent class. And i am trying to instrument child class' method using @Advice.FieldValue in the advice. When Child class is getting used, since this class is loaded before parent class, it is not able to instrument child class' method throwing Cannot locate field. How do i solve this ? One way is to use reflection in the advice. But it will have performance overhead. Any other way ?

**Comment by raphw** [comment]
That's tricky when using the default annotations. Ideally, you'd solve it differently, but I am sure you have your reasons.

You can register a custom `OffsetMapping`. Have a look how the offset mapping for a field value is defined in the `Advice` class and implement your own solution which avoids checks for the fields prior existence. Then, register this mapping using `Advice.withCustomBinding()` and use your own annotation instead of the one that is shipped with Byte Buddy.

**Comment by amar1019** [comment]
@raphw thanks for the reply. I tried with what i understood. 
```
	private static Advice.OffsetMapping.ForField getOffSetMapping(TypeDescription typeDescription) {
		return new Advice.OffsetMapping.ForField(typeDescription.asGenericType(), false, Assigner.Typing.DYNAMIC) {
			@Override
			protected FieldDescription resolve(TypeDescription typeDescription) {
				FieldList<FieldDescription.InGenericShape> fieldsList = typeDescription.getSuperClass().getDeclaredFields();
				for (FieldDescription.InGenericShape field : fieldsList) {
					if (field.getActualName().equalsIgnoreCase("testField")) {
						return field;
					}
				}
				return null;
			}
		};
	}
```

```
.method(ElementMatchers.named("add"))
.intercept(Advice.withCustomMapping().bind(TestAnnotation.class, getOffSetMapping(typeDescription)).to(TestAdvice.class))
```

```
@Retention(RUNTIME)
public @interface TestAnnotation{
}
```

typeDescription.getSuperClass().getDeclaredFields() is not returning whatever field i have added in the base class.

**Comment by raphw** [comment]
If the field is not yet visible or defined, but you can guarantee that it will exist later, simply return a `FieldDescription.Latent` where you specify the expected properties of the field yourself.
