### ISSUE TITLE
i want to get Method use advice

### ISSUE THREAD

**Issue by dragontree101** [raphw/byte-buddy#125]
i code is 
`@Advice.OnMethodEnter
  static Map<String, String> enter(@Advice.Origin Method method) {
  SomeAnnotation annotation = method.getAnnotation(SomeAnnotation.class)}
`
but has exception
`java.lang.IllegalStateException: Non-String type java.lang.reflect.Method arg0 for origin annotation
	at net.bytebuddy.asm.Advice$Dispatcher$OffsetMapping$ForOrigin$Factory.make(Advice.java:3960)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved.<init>(Advice.java:5210)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$ForMethodEnter.<init>(Advice.java:5555)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining.asMethodEnter(Advice.java:5136)
	at net.bytebuddy.asm.Advice.to(Advice.java:237)
.... `

@raphw  how can i get Method use advice annotation?  

before i use can get method  by
` @RuntimeType
  public static Object metrics(
      @SuperCall
      Callable<?> client,
      @Origin
      Method method) `

thanks very much

**Comment by raphw** [comment]
The `Advice.Origin` and `Origin annotations are a bit different. When you use the delegation approach, which is exposed by the `.method( ... ).intercept( ... )` API, you have more degrees of freedom. Using this API, Byte Buddy will alter a class file to override the method and to delegate to your actual advice method. If you added a parameter naming `@Origin Method m`, Byte Buddy would create a field with the `Method` reference and store it in the instrumented class.

With the `Advice` component, things are a bit different. For `Advice` instrumentations, Byte Buddy inlines your code into the instrumented method. As `Method` instances are no primitives to Java byte code, Byte Buddy cannot define a constant `Method` instance to exist as Byte Buddy would only be able to look up the `Method` instance dynamically such as you would do it yourself.

In order to access custom meta data from within the method, rather look into using custom annotations to provide this information as it is done with `Advice.withCustomMapping()`.

**Comment by dragontree101** [comment]
if i both use .method( ... ).intercept( ... ) API and Advice API ,  have any bad influence ？ if i want to get Method i use .method( ... ).intercept( ... ) and others use Advice API

**Comment by dragontree101** [comment]
i both use .method( ... ).intercept( ... ) API and Advice API, it works ok,
but i want to know Advice API's  performance and .method( ... ).intercept( ... ) 's performance  which is best? have any test data?

**Comment by dragontree101** [comment]
because of i custom a java annotation(@count(value="123")) on some methods,
actually i want to know the the method of annotation's value,  if i use Advice API,  have any way to get the value: "123"?

**Comment by raphw** [comment]
You can use `Advice.withCustomMapping().bind(MyAnnotation.class, myBinder)` to register an annotation that writes the above `value` directly into the method instead of accessing it at runtime. This is also a signigicant performance improvement as looking up a `Method` reference takes quite some time.

The most important difference between the `Advice` (`.visit( ... )`) and the delegation (`.method( ... ).intercept( ... )`) is that the former API guarantees to not alter a class file's format. To a user, any changes are completely invisible. Is is therefore only possible to add code to the beginning and the end of a method, not to change the actual code stack. All code is executed from within the instrumented class and it is possible to access private members of this class.

Using the delegation API, you can completely replace a method and invoke the original method from this method, if you want to. It often leads to an easier programming model as it is more intuitive to read as the inlined advice methods.

Performance-wise they are more or less equivalent. Both have a minimal impact on the inlining metrics of a JVM. The Advice component adds to a method's code size while the delegation approach adds to the call stack depth. Both can have negative impact but it rarely happens and it is difficult to predict what happens.

**Comment by dragontree101** [comment]
thanks very much!
i will study  how to use Advice.withCustomMapping().bind(MyAnnotation.class, myBinder), i will update some code to my byte buddy demo.

**Comment by raphw** [comment]
Great, good luck. Simply open this issue or create another one if you have further questions.
