### ISSUE TITLE
Trying to workaround Hostwap's restrictions. Question.

### ISSUE THREAD

**Issue by shot-mk** [raphw/byte-buddy#134]
Hi.
Sorry for my horrible english.
I am trying to implement field level security for domain objects. If not going too deep i want to intercept getter and setter of secured field of my domain object and add some authorization checks inside of it. And if the user is authorized to READ or WRITE to this field i'll call to original getter/setter with the help of `@SuperCall `annotation. The problem is that security configuration can be changed during life of application.
For example i have Book entity with field Name. And from the start it is unsecured field. Now Administrator changes security schema of application and this field needs to be secured and needs to include all security checking inside setter/getter. I can't do `rebase()` here because ByteBuddy adds some implementation specific fields and methods to save original method's code, and i am stopped by HotSwaps restrictions. My idea was to rebase all getter/setter in the beginning, before class was loaded to memory, with no logic inside, just calls to original methods. So ByteBuddy creates all infrastractional fields and methods. And then i was going `redefine()` the getter on demand (after security schema changes) and do all my permission evaluations inside, and in case when user is permitted for this action to go with reflection find the original getter by name (it need to be something like originalMethodName$original$someRandomStuff) and to call it. But when i was trying to implement this approach i get: `java.lang.UnsupportedOperationException: class redefinition failed: attempted to delete a method.`
While testing i was trying to implement this on a single method. Here is my code: 
This is initial rebasement of getter, that can become secured in runtime:

```
public class TestBean implements InitializingBean {
	@Override
	public void afterPropertiesSet() throws Exception {
		System.out.println("INITIAL INTERCEPTION");
		TypePool typePool = TypePool.Default.of(this.getClass().getClassLoader());
		new ByteBuddy().rebase(typePool.describe("com.test.model.Book").resolve(), ClassFileLocator.ForClassLoader.of(this.getClass().getClassLoader()))
		.method(ElementMatchers.named("getName"))
		.intercept(MethodDelegation.to(GettersSettersInterceptor.class))
		.make()
		.load(this.getClass().getClassLoader(), ClassLoadingStrategy.Default.INJECTION);
	}
}
```

Here is GettersSettersInterceptor code:

```
public class GettersSettersInterceptor {
	@RuntimeType
	public static Object intercept(@Origin Method method, @SuperCall Callable<?> zuper, @This Object currentInstance) throws Throwable {
		return zuper.call();
	}

	public static void intercept(@Origin Method method, @RuntimeType Object arg, @SuperCall Callable<?> zuper, @This Object currentInstance) throws Throwable {
		zuper.call();
	}
}
```

And here is code that is trying to redefine method in runtime. In this example i am using FixxedValue delegation. Just to check the concept:
```
		ByteBuddyAgent.install();
		Book book = bookService.findOne(203L);
		System.out.println(book.getName());
		new ByteBuddy()
			.with(TypeValidation.DISABLED)
			.redefine(Book.class)
			.method(ElementMatchers.named("getName"))
			.intercept(FixedValue.value("intercepted getName()"))
			.make()
			.load(Book.class.getClassLoader(),ClassReloadingStrategy.fromInstalledAgent());
		System.out.println(channel.getName());

```

And on the .load() line i am having : 
`java.lang.UnsupportedOperationException: class redefinition failed: attempted to delete a method`

I am thinking that it's because ByteBuddy is trying to redefine class as it is actually written, and not the one that is in memorry at the moment. 

So the question is if there is better or at least possible way to achieve required behavior.
Thanks.

**Comment by raphw** [comment]
When you are calling `.redefine(Book.class)`, you implicitly add a `ClassFileLocator` that reads the current class file from the underlying jar file. There is an alternative class file locator that reads the current class file via the Byte Buddy agent, i.e. `ClassFileLocator.ForAgent` that you need to use. 

However, you might want to use a different approach alltogether. I suggest you to look into one of the following alternative approches:

1. Instead of redefining `Book.class` using an interception, have a look at the `Advice` instrumentation which is limited in the sense that it can only add code before or after a method; it is however capable of changing a return value in the `OnMethodExit` advice.

2. Instead of changing the byte code in order to enable or disable a feature, simply use the agent to add the instrumentation a single time. Use a `MethodDelegation` instrumentation and check from the interceptor if the feature is enabled or disabled and act accordingly. The JIT compiler is very powerful and will detect that you only ever use one of the approaches and generate machine code that resemble exactly what you are trying to do; i.e. optimizing for the currently enabled path.
