### ISSUE TITLE
Support for Other JVM Languages

### ISSUE THREAD

**Issue by sirinath** [raphw/byte-buddy#14]
This is awesome. Is it possible to extent this so it can be easily used with other JVM languages with their idiomatic naming conventions. Especially Scala.

**Comment by raphw** [comment]
Hei Sirinath,
I am glad you like Byte Buddy. I tested with both Scala and Groovy which are the two JVM languages that I occasunally use

**Comment by sirinath** [comment]
Languages like Scala generate different names at the bytecode level. So you have to know exactly what something is complied into. It would be helpful if you can use the language level symbols which translate into the actual name / representation in bytecode. Also this is frequently changing in the case of Scala.

**Comment by raphw** [comment]
You are right, Scala is a problematic use-case in many relations. I do consider adding more Scala sensitive matchers at some point, the problem is however that these matchers would need to relate to a specific version of Scala as changes in the language would of course also affect the provided matchers.

I hope that I will find the time at some point to better analyze what changes are custom and to provide matchers that are least likely to fail. Up till now it is more or less the responsibility of the user to provide appropriate matchers or to, for example, only intercept methods on annotations instead of naming patterns when working with Scala.

**Comment by sirinath** [comment]
May be you can have a configuration file which match the Scala name with representation for the given version but transparent to the user. One this is defined user for the given version the user do not have to worry about what bytecode is generated underneath.

**Comment by raphw** [comment]
I thought about this and I came to the conclusion that this should not be a part of the core library but should rather be covered by an external library. The future of languages like Scala is uncertain and there are no guareantees about how their compilation is handled in the future.

If I added this fearure, I wanted to always be in sync with the compiler which is something I cannot promise. I therefore recommend Scala developers to use more explicit marks such as annotatations when identifying methods.
