### ISSUE TITLE
can not match lamda method

### ISSUE THREAD

**Issue by YongwuHe** [raphw/byte-buddy#1508]
When I need to do an target code usage search for all the methods in a certain class. I can't match to the lamda method, so some object codes cannot be replaced. Is there any way I can match to the lambda method.
ex: `memberSubstitution.on(isMethod())`

@raphw

**Comment by raphw** [comment]
This would require to match a invokedynamic instruction. This is not possible today, but could be added.

**Comment by YongwuHe** [comment]
This is how we do it now:
// byte buddy will ignore the method which is lambda. replace method need search all method(include lambda).
    private void removeIgnoredMethods(DynamicType.Builder<?> builder) {
        try {
            if (ignoredMethods == null) {
                ignoredMethods = DynamicType.Builder.AbstractBase.Adapter.class.getDeclaredField("ignoredMethods");
                ignoredMethods.setAccessible(true);
            }
            ignoredMethods.set(builder, new LatentMatcher.Resolved<MethodDescription>(none()));
        } catch (Exception e) {
            LogManager.warn("removeIgnoredMethods", e);
        }
    }`

**Comment by manoelcampos** [comment]
Hey guys, @YongwuHe was trying to match a lambda expression to transform its byte code, right? 
But there is no `isLambda()` matcher.

@raphw said it was not possible, but the issue was marked as resolved on release [1.14.7](https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.14.7). However, there isn't anything related to this on the release notes. I tried to look on the commit history but couldn't find anything related to "lambdas" either.

**Comment by raphw** [comment]
Lambdas can only be matched in code. They are not methods, but invokedynamic instructions. In `MemberSubstitution`, you can now intercept such lambdas.
