### ISSUE TITLE
Sometimes instrumentation fails when JRebel is deployed

### ISSUE THREAD

**Issue by orange-buffalo** [raphw/byte-buddy#174]
I have a problem with executing `Advice` instrumentation when JRebel agent is deployed to application. I understand that this is not a common use case, but still want to ask for help with this issue. 

When `@OnMethodEnter` advice returns a value, verification of instrumented class fails with exception:
```
java.lang.VerifyError: (class: org/aspectj/weaver/ReferenceType, method: getDeclaredInterfaces signature: ()[Lorg/aspectj/weaver/ResolvedType;) Incompatible object argument for function call
```

Without JRebel instrumentation succeeds, and class is loaded successfully when instrumentation is disabled and JRebel deployed.
 
I have [prepared a project](https://github.com/raphw/byte-buddy/files/425750/byte-buddy-test.zip) to demonstrate this behavior. In order to run it please update the following at line 56 of `pom.xml`:
```xml
<configuration>
  <argLine>-agentpath:PATH_TO_JRebel_DLL_OR_SO</argLine>
</configuration>
```
with path to [JRebel agent](https://zeroturnaround.com/software/JRebel/download/). And then execute `mvn test`. 

If you do not use JRebel or have no time to setup it, could you please advise what information / logs / anything would help in understanding the cause of this exception?

**Comment by raphw** [comment]
The value returned by the `@OnMethodEnter` needs to be added to the local variable array of the method. For this to happen, any other local variables are moved by an offset one by Byte Buddy. It seems like the JRebel agent hard-codes indices into its instrumentation, i.e. expects an exact byte code pattern to be present when instrumenting code.

I do not currently have a JRebel license. Can you run your program with `-Dnet.bytebuddy.dump=/some/location` and send me the corrupted class file in question?

**Comment by orange-buffalo** [comment]
I was also thinking that JRebel relies on specific patterns in class file. I disabled AspectJ plugin for JRebel (as class under the test in from AspectJ framework) - this should have prevented instrumentation. But the result was the same, although JRebel log stated plugin was disabled. We do not know how JRebel is implemented, maybe some other code of the tool instruments the class anyway. 

Here is [a dumped class file](https://github.com/raphw/byte-buddy/files/426627/org.aspectj.weaver.ReferenceType.1471595599440.zip).

I believe there could be other instrumentation libraries that heavily rely on bytecode structure. Could it be possible to append the value returned from `@OnMethodEnter` to the end of local variables array to avoid shifting existing variables? With this approach risks of collisions probably would be minimized..

**Comment by raphw** [comment]
The problem is that a Java agent will always change the byte code of a method. That's its main reason to be. Byte code gives a big degree of freedom and it is up to the instrumenting library to ensure that the byte code remains valid no matter what the input is. 

Let's say that you wanted to instrument a method to stub out another method call. You would need to find that method call and replace it with something else, like a constant. Any subsequent agent would no longer be able to find this method call and the indices of all other instructions would have changed, as well. The Java agent needs to know how to react to this as an implementation is not part of the method's contract. Byte Buddy does not change any method contracts, i.e. retains the signature and never changes a method's parameters.

Most visitors built using ASM, the most popular byte code processing library in the Java space, imply local variable (re-)sorting which is somewhat necessary for many "on the fly instrumentations" such as Byte Buddy. Therefore, it is very unlikely that Byte Buddy will ever attempt to work around such limitations. This is a general issue.

Finally, the class file you sent me seems legal. ASM's `CheckClassAdapter` does not find any problems with the class. I assume this is what happens:

1. JRebels agent comes first. It parses the class file and caches some indices of variables that it needs to patch regularly.
2. The Byte Buddy instrumentation comes second, it changes these indices.
3. The class is loaded for the first time.
4. The JRebel agents wants to patch some index it cached but that was changed by Byte Buddy.

One way to break this chain - if my assumption is correct - would be to apply the Byte Buddy transformer first. Simply pack your transformer as a Java agent and add it on startup **before** the JRebel agent. This way, JRebel would cache the right indices.

**Comment by orange-buffalo** [comment]
Actually, the problem comes from real application where transformer is a java-agent. I tried to apply JRebel agent after my custom one, but with no luck, result was the same.
Verification error does not provide anything else but starcktrace to the place class is loaded and the message from issue description. 

I completely understand your concerns and agree with what you've said. As far as I know, JRebel uses Javassist, maybe there is an issue in the library or the way it is used. I will contact JRebel and ask them to shed some light on what they do with this class. 

Thanks for your help!

**Comment by raphw** [comment]
I already contacted a JRebel engineer that I know but please file an official issue. There is always a chance that there is a bug in Byte Buddy but without a license, I cannot reproduce the issue and only guess.

**Comment by raphw** [comment]
I received a first feedback that this is a problem in JRebel and they look into it. I will keep you posted.

**Comment by orange-buffalo** [comment]
Cool, thank you! I also provided JRebel team with details in related support request.

**Comment by raphw** [comment]
I already got feedback and it turns out it is indeed a problem in Byte Buddy. The `Advice` component did not adjust some debugging information of the class file which was used by JRebel to gain some insights that would otherwise need to be inferred in a more complex manner.

Can you try out the current state?

**Comment by orange-buffalo** [comment]
I checked it on master, the problem is fixed. Again, thank you for your help!

**Comment by raphw** [comment]
Perfect, thanks for the report. I will release a new version next week.
