### ISSUE TITLE
Redefining java.lang.System breaks when switching 1.4.1 -> 1.4.2

### ISSUE THREAD

**Issue by devcsrj** [raphw/byte-buddy#203]
I've been playing with ByteBuddy by redefining the behavior of `java.lang.System#exit`, using:

```java
AgentBuilder agentBuilder = new AgentBuilder.Default()
    .with( InitializationStrategy.NoOp.INSTANCE )
    .with( RedefinitionStrategy.REDEFINITION )
    .with( TypeStrategy.Default.REDEFINE )
    .with( Listener.StreamWriting.toSystemOut() )
    .type( named( "java.lang.System" )  )
    .transform( // transform method signature omitted
                      
          return builder.method( named( "exit" ) )
             .intercept( ExceptionMethod.throwing( SecurityException.class, "Not supported" )) );
```

This'll work, at most 1.4.1. Switching to 1.4.2+ will break this. Even after looking at the [1.4.1->1.4.2 diff](https://github.com/raphw/byte-buddy/compare/d406ab8...10593f8), I had no luck.

Thoughts?

Edit: *Break* as in ByteBuddy no longer redefines `System` ( `exit` no longer intercepted ).

**Comment by raphw** [comment]
I think it is because Byte Buddy has started ignoring `java.*` types by default. Many users had problems by accidentally instrumenting types from the bootstrap path without intending this, thus breaking their apps. You need to explicitly opt-in for such instrumentation adding `ignore(none())` to your above builder.

I would also recommend you adding `disableClassFormatChanges()` to your builder and to match `is(System.class)` as a more type-safe alternative.

**Comment by devcsrj** [comment]
>  ..has started ignoring java.*... adding ignore(none()) to your above builder.

That did the trick! Above snippet works now with the latest (1.4.24).

> disableClassFormatChanges()... is(System.class)

Man, you're a life saver.

> accidentally instrumenting types from the bootstrap path

I think I read somewhere that modifications to core classes (-Xbootclasspath) Oracle's License agreement. Does modification via instrumentation, like the one above, count?

**Comment by raphw** [comment]
No, such modifications are allowed. You are not dllowed to ship a modified JDK for compatibility with other apps.
