### ISSUE TITLE
Is there any way to interceptor the class that the prefix of the package is "java.rmi"?

### ISSUE THREAD

**Issue by ascrutae** [raphw/byte-buddy#236]
I just to use  this [example](https://gist.github.com/raphw/34c0e2fffe2ee7b4f02f), but it didn't work. I also try to  start the example with the param "-javaagent" . it also didn't work.

**Comment by ascrutae** [comment]
oops, My byte buddy version: 1.5.7

**Comment by raphw** [comment]
Newer version of Byte Buddy ignore classes on the bootstrap class path by default as most people do not want to instrument those classes. In order to enable bootstrap instrumentation, you have to specify your own ignore matcher such as `.ignore(ElementMatchers.nameStartsWith("net.bytebuddy."))` where all Byte Buddy classes would be excluded.

I updated the example.

**Comment by ascrutae** [comment]
Thanks for you response. it works
