### ISSUE TITLE
(Question and Discuss) About Reloading the class.

### ISSUE THREAD

**Issue by wu-sheng** [raphw/byte-buddy#237]
Hi, as you know, I use byte-buddy to build my tracer agent. And I want to discuss with you about reloading a class.

Right now, I use `AgentBuilder` and `AgentBuilder.Transformer` to intercept classes and their methods. It works fine.
But I want to provide a new characteristic ( not sure is it possible for recent JVM ):
* Use an web UI to config the some classname or methodname, and these configs will to sync to the javaagent ( through some rpc ). Then these classes will be intercepted.
* And before this happens, not changes happened when it's loaded. Before config sync, these classes most likely have be loaded by application.

I fine a chapter named `Reloading a class` in your doc. You demo like this:
```java
ByteBuddyAgent.install();
Foo foo = new Foo();
new ByteBuddy()
  .redefine(Bar.class)
  .name(Foo.class.getName())
  .make()
  .load(Foo.class.getClassLoader(), ClassReloadingStrategy.fromInstalledAgent());
assertThat(foo.m(), is("bar"));
```
This seems very attractive but not fit entirely. It depends on `Byte Buddy's agent jar`

Can you teach me, how to do something like this, in my agent?

And another question is, if I intercept all possible classes, but do nothing in the interceptor ( directly call original class ), will this cost too much? 
I assume the answer is **TRUE**, so I ask the previous question about reloading a class.

**Comment by wu-sheng** [comment]
BTW, @ascrutae

**Comment by raphw** [comment]
You can configure an `AgentBuilder` to activate a `RedefinitionStrategy.RETRANSFORM`. Doing so, Byte Buddy registers the agent to also transform already loaded classes. Byte Buddy picks up any retransformation once this strategy is activated. You can trigger a retransformation using `Instrumentation::retransformClasses`. All you would need to do would be to call this method with supplying the classes in question.

When applying retransformation, you should also activate `.disableClassFormatChanges()`. This disallows certain operations which most VMs do not support for retransformation. Typically, you would use this feature in combination with an `Advice` class.

**Comment by wu-sheng** [comment]
1. Can you give me a quick start about retransform?
1. What will `disableClassFormatChanges` disable? If I want to add a method interceptor? I see your doc said something about change class constructions. Can you give me a short list about what can be done when retransform.

**Comment by raphw** [comment]
With `disableClassFormatChanges`, you cannot longer add methods or fields. Some of Byte Buddy's components do this implicitly, for example if you apply a `MethodDelegation` to an instance rather than to a static method where Byte Buddy needs to store the instance in a static field within the transformed class.

Also, you cannot retain the original code of any transformed class when applying a method delegation. The result will be a `ByteBuddy::redefine`, not a `ByteBuddy::rebase`. If you want to enhance existing code, you can add code prior and after an existing method using `Advice` via `DynamicType.Builder::visit` where you inline the advice method's code.

You can have a look at [Stagemonitor](https://github.com/stagemonitor/stagemonitor) which implements such an agent using `Advice`.

**Comment by raphw** [comment]
With help of `tools.jar`, you can attach to a JVM at runtime rather than at startup. This is often working well for debugging tools that are primarily using JDKs anyways. We do for example use it in Mockito for the inline mock maker that allows you to mock final methods and classes. I also figured out a way to make it work in Linux SDKs by mimicing the attach API's protocol.

Stategmonitor uses the attachment how it is recomended. It attempts an installation if no javaagent was provided. Otherwise, you need to add the byte buddy agent manually (minimal jar) and Byte Buddy picks it up automatically. The `EhCacheAttachmentProvider` is added as EhCache attempts the same runtime attachment and breaks loading the (native) library on some JVMs, so it is rather a workaround to a limitation of older VMs.

Note that you can attach to a VM even if it is run on a JRE as long as you attach from a JDK if you make an external attachment.
