### ISSUE TITLE
Resubmitter use case

### ISSUE THREAD

**Issue by dpsoft** [raphw/byte-buddy#253]
In what use cases the Resubmitter feature is useful?

**Comment by CodingFabian** [comment]
Imagine you wrote a transformer, this one is now triggered in two way:
A) the JVM has loaded the class already. This happens directly after you install a transformer. You can navigate the loaded class hierarchy.
B) the JVM loads the class for the first time. While ByteBuddy helps you to still work on the hierarchy (basically ByteBuddy parses it from the raw class files for you) there can be cases where ByteBuddy is unable to resolve the class hierarchy properly.

In case B) you can use the resubmitter to "schedule" basically the case A happening: You bail and let the JVM load the class and its hierarchy. Now that the class was loaded you can for sure access the whole loaded type hierarchy.

There are a few scenarios where this can happen. For example in OSGi, where the delegation model prevents the resource lookup bytebuddy does (the classloader might refuse to load a class as resource, but give it out as class)
Or some obscure code generation, or just plain buggy classloaders.
(seen all 3 variants :-))

**Comment by dpsoft** [comment]
@CodingFabian thank you for your clear and helpful explanation!!!

**Comment by cristianspinetta** [comment]
@CodingFabian when you say "ByteBuddy is unable to resolve the class hierarchy properly", what does it mean?
I say, how does it possible that a class is not visible for ByteBuddy the first time and then it becomes visible?

**Comment by CodingFabian** [comment]
the transformer gets per Instrumentation API the "raw bytes" of the class file. In that class you might reference superclass (which also has not been loaded because this class is the first one using it)
ByteBuddy will then request the "raw bytes" of the superclass and parse it.

When you deal with a class that has been loaded already, the JVM already has resolved the superclass by whatever classloaders that were responsible for doing so.

as said, the core difference is that in the one case ByteBuddy uses getResource() to get the "raw bytes", in the other case you can access getClass() to get the loaded class. With compliant classloaders it doesn't make a difference, but that's not always the case :)

**Comment by cristianspinetta** [comment]
Very good explanation, thanks!

I still can not find an example in which this may be possible. Just to be more clear, can you tell me if the following is a possible case?

A `ClassFileTransformer` is instrumenting a class method, adding a piece of bytecode with a super type call. In this case, the JVM is not be able to accept the new bytecode due to the super type is not still loaded?

**Comment by CodingFabian** [comment]
no that would work normally. Imagine that your ClassFileTransformer does not yet know what to do, because it is interested only in subclasses of a certain class. therefor you would need to navigate the hierarchy to decide wether to modify the class or not.

**Comment by raphw** [comment]
Thanks for the explanation.

Basically, Byte Buddy relies on the readability of class files. This is normally given as classes are stored in class files together with resources. It is a class loader's responsibility to provide these items. If you add a resource `my.properties` to a jar, publish it then you expect to read these properties at runtime via querying your class loader.

Byte Buddy does something similar. When you request information to a class that is linked in an instrumented type, it requests a `.class` file as a resource and parses the class file into a `TypeDescription`. This way, you can query for information like `agentBuilder.type(isSubtypeOf(Foo.class)`. If some class `Qux` is found which is a subclass of `Bar` which is a subclass of `Foo`, Byte Buddy needs to parse both the class files of `Qux` and `Bar` to answer the question of subtyping. At this time it is not yet possible to load `Bar` as you must not load new types during instrumentation which is why the above routine is activated.

If this fails and your instrumentation can be applied onto a loaded type, you can fall back to retransformation in a second step.

**Comment by dpsoft** [comment]
Thanks for the explanation. So always is a good idea have a Resubmitter ;)

**Comment by cristianspinetta** [comment]
Thank you very much for your time and this useful explanation!
It's very clear the motivation to introduce this feature.
