### ISSUE TITLE
Quest about the parameter of method wrap in AsmVisitorWrappe.java

### ISSUE THREAD

**Issue by ascrutae** [raphw/byte-buddy#279]
The type `net.bytebuddy.jar.asm.ClassVisitor` as parameter in the jar that download from mvn repository, but The type `org.objectweb.asm.ClassVisitor` as parameter in the source code. Which one are correct?

Thanks 

Xin

**Comment by raphw** [comment]
Byte Buddy repackages ASM to avoid version conflicts with other versions as ASM changed its API quite a lot in its older versions. In the source code, the original signature is referenced which is why you observe this mismatch.

If you want to make extensive use of ASM, consider using the `byte-buddy-dep` package.
