### ISSUE TITLE
Circular interception & java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by basu76** [raphw/byte-buddy#292]
Hi,
I am new to byte-buddy, just started writing an agent to intercept http requests. The environment on which the agent runs would be both regular runtime and osgi runtime. 

I have 2 issues and a question.

1) Is there an advantage of using static method for interceptor vs non static. I saw that with a non static interceptor method a new object is created and attached to every instrumented class.

2) My interceptor gets called in a loop as I am invoking another method with the same name (I was able to work around it, but I know it is not the right way). With AspectJ I had used  !cflow(within( to avoid the same one being called over and over

```
new AgentBuilder.Default()
                    .type(ElementMatchers.named("org.eclipse.jetty.servlet.ServletHandler")).transform(
                            (builder, type, classLoader, module) ->
                                builder.method(ElementMatchers.named("addFilterWithMapping"))
                                .intercept(MethodDelegation.to(new HTTPRequestInterceptor()))
            ).installOn(instrumentation); 

```
//Code in Interceptor

```
Method filterWithMappingMethod = thiz.getClass().getMethod("addFilterWithMapping", Class.class, String.class, EnumSet.class);
                filterWithMappingMethod.invoke(thiz, XYZFilter.class, "/*", EnumSet.of(javax.servlet.DispatcherType.REQUEST));
```

3) After getting past the above issue in a crude way - ran into java.lang.NoClassDefFoundError: javax/servlet/Filter . How do I make this class visible to agent ?

thank you

**Comment by basu76** [comment]
any one ? any pointers ?

**Comment by raphw** [comment]
A Java agent is loaded on the Java class path where only classes added to it and included by your agent are available. If you did not add the `Filter` class, this exception is to be expected.

If you are using a `MethodDelegation`, you need to make sure that all types are compatible what is difficult in an OSGi environment where you would need to make sure to resolve the exact class for the `Filter` in the delegation target. This would be achieved most easily by injecting or adding the delegation class into the OSGi module. Therefore, I guess that using the `Advice` class is your best approach where the code is inlined into the target class and this is not an issue.

However, Byte Buddy needs to resolve the `Filter` class for applying the instrumentation where it needs to look up the filter class from the target class loader. You can use `AgentBuilder.Transformation.ForAdvice` to do so where Byte Buddy uses both your agents class loader and the intrumented class's class loader to resolve types such that the `Filter` can be found. Use the named transformer instead of referencing the loaded advice class with `Advice.to( ... )`.

**Comment by basu76** [comment]
Thank you. I should have updated this yesterday night, when I got it working.  Did very similar to what you have suggested. Added servlet API jar to agent jar & used advice API.

In the advice API I am calling a similar method as what the advice is applied to, this results in a circular call to the advice and finally java.lang.StackOverflowError . Is there any way to prevent it ?

thank you
