### ISSUE TITLE
StackOverflow on calling inherited method 

### ISSUE THREAD

**Issue by sirvaulterscoff** [raphw/byte-buddy#301]
I came across a certain case when ByteBuddy causes StackOverflow exception to appear.
How to reproduce the problem
```
public class MainTest {

    @Test
    public void callMethodFromBaseClass() {
        assertNotNull(new Outer().innerCreateView());
    }

    
    public static class Outer extends Inner<InnerView> {
        @Override
        protected View innerCreateView() {
            return new InnerView() {
            };
        }
    }

    public static class Inner<T extends InnerView> extends Abstract {

        @Override
        protected View innerCreateView() {
            return new InnerView() {
            };
        }
    }

    public static abstract class Abstract<T extends View> extends Base<T> {

    }

    public static abstract class Base<T extends Component> {
        public T createView() {
            return innerCreateView();
        }

        protected abstract T innerCreateView();
    }

    public interface Component {

    }

    public interface View extends Component {
    }

    public interface InnerView extends View {
    }

}
```

Without any modifications test passes.  If i add ByteBuddy agent (scroll bellow) test fails with StackOverflow. Moreover, the problem arises only with the following hierarchy Outer -> Inner -> Abstract -> Base. If i reduce the hierarchy to Outer -> Inner -> Abstract thus removing the Base problem dissapears.

The following code is used for agent
```
        new AgentBuilder.Default()
                .with(AgentBuilder.TypeStrategy.Default.REBASE)
                .type(ElementMatchers.<TypeDescription>any())
                .transform(new AgentBuilder.Transformer() {
                    public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule module) {
                        System.out.println("Processing " + typeDescription.getName());

                        final ElementMatcher.Junction<MethodDescription> methodFilter = ElementMatchers.not(ElementMatchers.isHashCode().or(ElementMatchers.isEquals()).or(ElementMatchers.isClone()).or(ElementMatchers.isToString()));
                        UsageInterceptor.registerType(typeDescription, methodFilter);
                        return builder
                                .method(methodFilter)
                                .intercept(MethodDelegation.to(UsageInterceptor.class)
                                        .andThen(SuperMethodCall.INSTANCE));
                    }
                })
                .installOn(inst);
```

Contents of UsageInterceptor class is  totaly irrelevant (it can actualy be empty).
Please let me know if you need this as a test case (actualy i failed to write a correct test case with agent installing, i will be gratefull if you point me to examples)

**Comment by raphw** [comment]
I just tried and my example terminates without a stack overflow. Maybe it has to do with ` UsageInterceptor.registerType(typeDescription, methodFilter)` which I do not understand what does.

As for a reproduction, this would help a lot. Have a look at the `byte-buddy-agent` project where you can invoke `ByteBuddyAgent.install()` to get hold of an instance of `Instrumentation`. Use it to install your agent and call your instrumented code afterwards.

**Comment by sirvaulterscoff** [comment]
I've uploaded test cases here https://github.com/sirvaulterscoff/bytebuddy-301

Im realy frustrated cause i failed to reproduce the problem inside unit tests. Though unit-test also produces an error. Any way:

`mvn install -Pagent` creates agent jar and runs executable jar with agent. This clearly reproduces my case
`mvn test` fails with java.lang.ClassFormatError: Illegal field modifiers

**Comment by raphw** [comment]
The first problem is caused by a missing validation in Byte Buddy. It is not allowed to define a non-final field in an interface what is necessary to implement your way of interception for the `Component` type. With Java 8, it is possible to intercept default methods which is why this is possible. I did now add the validation. You can avoid the problem by setting `type(not(isInterface()))` as a matcher.

The stack overflow error comes from your too lax method matcher. You probably want to match `.method(isDeclaredBy(typeDescription).and(methodFilter))`. Otherwise, you also override methods of super types. This results in an endless loop as you override the `innerView` method to call itself.

**Comment by sirvaulterscoff** [comment]
Thanks for commenting on issue, but i don't actualy see your point about StackOverflow - why endless-loop happening in my case. Moreover, if i remove Base from  Outer -> Inner -> Abstract -> Base hierarchy problem vanishes. To my mind,  Outer -> Inner -> Abstract  is more than enough to introduce enless-lopping if that was the case

**Comment by raphw** [comment]
I double-checked and found out what happened. The problem is the fragility of the base class. For your given setup, if you overridde the `createView` method in `Inner`, javac will create a bridge for the generic return type where the actual method returns `View` and the bridge `Component`, casting the result.  The bridge call is done virtually.

If you now override the `Outer` class to also overridde `createView`, the super method call will change from invoking the method returning `Component` to the method returning `View` to avoid the recursion. However, if you change the `Outer` class first and later change the `Inner` class, with javac, you suffer the same problem. It is a form of *fragile base class* problem. 

Byte Buddy struggles with the same challange as it does not know that `Inner` is changed while instrumenting `Outer`. `Inner` is only loaded after `Outer` which makes this change unclear.

The solution is to not *add* methods that imply bridges. Thus, limiting instrumentation to already declared methods by excluding any methods that are not declared by the instrumented type as I suggested.

**Comment by sirvaulterscoff** [comment]
Sorry, forgot to mention, that provided solution works perfectly, was interested in detailed problem description though.
Thank you for a very detailed description.
