### ISSUE TITLE
Error when using FixedValue to implement default method on interface

### ISSUE THREAD

**Issue by joebandenburg** [raphw/byte-buddy#317]
I'm trying to use Byte Buddy to create an interface with a default method that returns a fixed value that is a non-primitive type.

```java
new ByteBuddy()
    .makeInterface()
    .defineMethod(name, returnType, Visibility.PUBLIC)
        .intercept(FixedValue.value(value))
    .make();
```

Byte Buddy throws an exception when calling `make()`:

```
java.lang.IllegalStateException: Cannot only define public, static, final field 'value$16r3000' for interface type
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ValidatingClassVisitor$Constraint$ForInterface.assertField(TypeWriter.java:2225)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ValidatingClassVisitor$Constraint$Compound.assertField(TypeWriter.java:2565)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ValidatingClassVisitor.visitField(TypeWriter.java:1885)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$FieldPool$Record$ForImplicitField.apply(TypeWriter.java:187)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForCreation.create(TypeWriter.java:4156)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1633)
```

Looking at the code, `FixedValue.value(Object value)` delegates to `FixedValue.reference(Object value)` in my case (the type of `value` is `List<String>`). It seems that this attempts to create a non-final field on the interface, which is disallowed by `ForInterface.assertField()`.

I'm using version 1.7.1.

Is this a bug in `FixedValue`, `ForInterface` or am I doing something stupid?

**Comment by raphw** [comment]
Hei,
the problem is that Byte Buddy can only define a field and place a value inside of it after a type is loaded. Using reflection, it is in theory possible to change the value of a final field but future versions of Java are unlikely to support this, therefore the field is not final. At the same time, all fields of an interface must be final, what raises this conflict that is detected by the type validator.

What you could do would be to use `FieldAccessor` to read a value from a field that you define yourself. You can define a static initializer (by intercepting `isTypeInitializer`) using `Advice` where you can assign the field in Java code. Byte Buddy then inlines this Java code into your classes static initializer, thus creating a valid Java class.

**Comment by joebandenburg** [comment]
Hi @raphw,

Thanks for the quick reply. I'm trying to understand your instructions for working around the problem. Could you provide a code example of what you are suggesting?

This is what I've got so far:

```java
new ByteBuddy()
    .makeInterface()
    .defineField(name + "$field", returnType, Visibility.PUBLIC, Ownership.STATIC, FieldManifestation.FINAL)
        .initializer(Advice.of(...))
    .defineMethod(name, returnType, Visibility.PUBLIC)
        .intercept(FieldAccessor.ofField(name + "$field"));
    .make();
```

After reading the documentation for `Advice`, I'm not sure how to apply it to solve my problem. I'm also unsure of what you mean "intercepting `isTypeInitializer`".

**Comment by raphw** [comment]
What you would need to do would be something like:

```
.method(isTypeInitializer()).intercept(Advice.of(MyAdvice.class))

class MyAdvice {
  static void advice(@Advice.FieldValue(value = "foo", readOnly = false) List<String> field) {
    field = Arrays.asList("a", "b");
  }
}
}
```

The only requirement is really that the field must be a constant; therefore, it must be initialized from within the interface type.
