### ISSUE TITLE
Allow intercepting constructors with try catch where exceptions are automatically rethrown

### ISSUE THREAD

**Issue by raphw** [raphw/byte-buddy#375]
It is allowed by the JVM to wrap constructors in try-catch blocks as long as the exception is rethrown at the end of a constructor. This should make it possible in Byte Buddy to allow interception of constructors.

**Comment by paplorinc** [comment]
Related: http://mail.openjdk.java.net/pipermail/amber-spec-experts/2018-March/000320.html

> Historically, this() or super() must be first in a constructor. This restriction was never popular, and perceived as arbitrary. There were a number of subtle reasons, including the verification of invokespecial, that contributed to this restriction.  Over the years, we've addressed these at the VM level, to the point where it becomes practical to consider lifting this restriction, not just for records, but for all constructors.

**Comment by raphw** [comment]
Thanks for the hint, I really need to get onto this.

It seemed simple at first but as of now, Byte Buddy does not duplicate the exit advice code. To allow for this kind of rethrow, it is however not allowed to add any conditionals into the last return of the constructor in case an exception was catched what requires a larger rewrite of the advice component than what I hoped for.

**Comment by paplorinc** [comment]
How difficult would it be to add the try-catch after the super/this calls?
In that case we would obviously miss the parent exceptions, but at least be able to intercept local ones.

**Comment by raphw** [comment]
I considered this, however, constructors can be arbitrarily complex. There is no good way to detect the super call without flow analysis. I am still trying out things which is why this has not made it into the library yet.

**Comment by kriegaex** [comment]
Latest news from the [comment thread under an answer](https://stackoverflow.com/a/47262728/1082681) by @raphw on StackOverflow by user [Holger](https://stackoverflow.com/users/2711488/holger) who seems to know a lot about the JVM and byte code:

> Unfortunately, the HotSpot JVM violates the specification more than often and sometimes, like in this case [even deliberately](http://mail.openjdk.java.net/pipermail/hotspot-dev/2017-January/025781.html). By the time I wrote the comment, I had a working example and didn’t know that the authors (or one of them) of the most widespread JVM implementation were about to break it. It still works when lowering the class file version and not using stack maps, but that’s not a viable strategy for the future…

So, as sad as I also feel it is, unless there is no evidence of the opposite, I think we can close this ticket because of non-feasibility. 😟

**Comment by raphw** [comment]
Yes, I saw Michaels complaint on the mailing list. I had a suspicion that this would go away some time, the folks at Oracle never liked this potential integrity issue. I will still try to think of something; potentially one could interrupt the exception handler upon the invokespecial invocation, but this does of course not make things easier.

**Comment by kriegaex** [comment]
> suspicion that this would go away some time

Well, at least since Java 8, I tried 8-14, same behaviour. The whole thing works of course when running the test JVM with `-noverify`, but that is not nice. Generally, I like the byte code verifier as such, as long as it does not stop me doing benevolent transformations, which in this case it does.

Just let me know if you need some transformed class files as a starting point, even though I have created them with Javassist and not with ASM as is your usual practice because ASM is a BB dependency already. I removed the code generating `try-catch + rethrow` or `try-finally` from my current revision already, but I tagged the version in which I could generate that kind of stuff.

**Comment by raphw** [comment]
This is no longer legal in Java, unfortunately.

**Comment by kriegaex** [comment]
Please elaborate. I just ran my constrructor mock tests for Sarek on JDK 17, and they are still passing.

**Comment by raphw** [comment]
HotSpot does no longer allow to set a *TOP* frame for the value that might be an initialized this or an non-initialized this. It's been breaking some tooling but the OpenJDK team was pretty clear that they do not want to revert it.

**Comment by kriegaex** [comment]
Thanks for the explanation. Sounds like we really have to bury this one, then.

**Comment by raphw** [comment]
Unfortunately. I have played with a prototype, but constructor super calls can really become arbitrarily complicated. Therefore, I am still looking for a better solution before I commit the library to a given pattern.
