### ISSUE TITLE
Incompatible Class Version

### ISSUE THREAD

**Issue by realark** [raphw/byte-buddy#420]
Hello, I'm a developer of the Datadog APM agent. We use bytebuddy to instrument classes. Thank you for all your work on Bytebuddy. It's a fantastic tool.

Our instrumentation won't apply to pre java 5 classes due to class incompatibility.

> com.ibm.as400.access.AS400JDBCConnection for transformation: Cannot write type to constant pool for class file version 

https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/dynamic/scaffold/TypeWriter.java#L2495

Any recommended workarounds for this?

Would it be safe to simply upgrade the class' version (presuming the class file format is backwards compatible)?

**Comment by raphw** [comment]
Thanks, glad you like the tool.

Unfortunately, other than the Java programming language, Java byte code is not backwards compatible.

However, for class file constants, Byte Buddy offers a correction mechanism since that is the most common incompatibility. Register the TypeConstantAdjustment which should take care of that problem.

By the way, Java 6 byte code is the most compatible byte code version as of today which you should use for your Advice code to maximize compatibility.

**Comment by realark** [comment]
Thanks Raph, good to know. The TypeConstantAdjustment did the trick.
