### ISSUE TITLE
Defect: Second call of ModifierAdjustment is ignored

### ISSUE THREAD

**Issue by thekingnothing** [raphw/byte-buddy#478]
I'm working on migration PowerMock from Javassist to ByteBuddy. The main idea of PowerMock is that a class goes thought set of transformers which modified its bytecode to enable different mock features like mocking new call, suppress constructor call and so on. 

To be able to suppress constructor PowerMock adds `defer constructor` to all classes. It is a public constructor with only one parameter. So if a constructor should be suppressed the deffer constructor is called. In addition, PowerMock makes all constructors public, it makes easier mocking latter. 

However, a test class should have only one public constructor. The previous approach was: 
- make deffer constructor  non-public 
- restore all modifier as it was before 

With ByteBuddy such approach does not work, because if I try to run something like this 

```
        final TypeDescription typeDefinition = typePool.describe(original.getName()).resolve();
        Builder<Object> builder = new ByteBuddy()
                                      .rebase(
                                          typeDefinition,
                                          ForClassLoader.ofClassPath()
                                      );
            builder.visit(new ModifierAdjustment()
                                 .withConstructorModifiers(Visibility.PUBLIC);

           builder
                   .visit(
                       new ModifierAdjustment().withConstructorModifiers(
                           Visibility.PRIVATE
                       )
                   );
```

Then the result that all constructors are public. Please, find the full example [here](https://github.com/thekingnothing/bytebuddy-twice-modification-issue) 

I'm trying now to change approach: do not create a defer constructor and do not change modifiers of a test class at all, so it's not a blocker for me right now.

**Comment by raphw** [comment]
The builders are immutable, do you assign the builder to override the old reference in your code?

**Comment by thekingnothing** [comment]
Yep, of course. In the example I have reproduced the issue and approach how it works in PowerMock.


```
Builder<Object> builder = new ByteBuddy()
        .rebase(
        typeDefinition,
        ForClassLoader.ofClassPath()
        );

        for (Transformer transformer : transformers) {
        builder = transformer.transform(builder);
        }
```

All other transformation in chain works fine.

Best Regards,
Arthur Zagretdinov


On 27 May 2018, at 15:10, Rafael Winterhalter <notifications@github.com<mailto:notifications@github.com>> wrote:


The builders are immutable, do you assign the builder to override the old reference in your code?

**Comment by raphw** [comment]
Ok, I got some time to look into the sample. I see how this is confusing but it is actually expected behavior:
1. With `builder.visit(...)`, you are registering a low-level transformation that applies during writing the byte code and which does not interfere with Byte Buddy's `TypeDescription` representation. Therefore, any element matcher only sees a method in their original form.
2. Visitors are registered in their registration order, i.e. the first visitor is applied last. With modifier transformation, this means that the last visitor will actually define the modifier.

With this in mind, you cannot expect a transformation from the first step to be visible to the second transformer. The `MakeMarkerInterfaceConstructorNonPublicTransformer` does therefore not see the changes of the `MakePublicTransformer`. Also, the `MakePublicTransformer`, being registered first, will be the last to being applied such that it always defines the modifier.

This is of course not the greatest API behavior and I wish it was different but this requires a bit of a rewrite to offer a better solution. Maybe this can be a change in some 2.0 version some day but for now, this is what I can offer.

**Comment by thekingnothing** [comment]
Thank you for clarification. Yeah, I agree that it's not behaviour that you expect, however, now I know about it and I will keep in mind. Anyway, I already implemented the approach that defer constructor is not created for a test class and modifier is not changed also.

**Comment by raphw** [comment]
I am planing an enhancement of the type modelling API to incorporate such changes which is tracked here: https://github.com/raphw/byte-buddy/issues/479

Please reopen the ticket if you have further questions.
