### ISSUE TITLE
Redefine class including anonymous inner classes.

### ISSUE THREAD

**Issue by adamjryan** [raphw/byte-buddy#536]
I am trying to redefine a class that contains an anonymous inner class and when it comes to accessing what should be a copy of the definition in the new class it throws an exception stating it cannot access the anonymous class contained in the original class. Here is an example demonstrating the the scenario.

    import net.bytebuddy.ByteBuddy;

    class Scenario
    {
        public interface NumberFactory
        {
            Number newNumber();
        }
    
        public static class NumberFactoryTemplate implements NumberFactory
        {
            public Number newNumber()
            {
                return new Number()
                {
                    public int intValue(){ return 0; }
                    public long longValue(){ return 0; }
                    public float floatValue(){ return 0; }
                    public double doubleValue(){ return 0; }
                };
            }
        }
    
        public static void main( String[] args ) throws Exception
        {
            NumberFactory numberFactory = new ByteBuddy().redefine(NumberFactoryTemplate.class)
                .name("NewNumberFactory")
                .make().load( NumberFactoryTemplate.class.getClassLoader() ).getLoaded()
                .newInstance();
            Number number = numberFactory.newNumber();
        }
    }

On calling numberFactory.newNumber() the following exception is thrown:
` Exception in thread "main" java.lang.IllegalAccessError: tried to access class Scenario$NumberFactoryTemplate$1 from class NewNumberFactory `

Is there something I need to do to have the anonymous class redefined also or is this a deficiency in the library?

**Comment by raphw** [comment]
This is because by `.load(NumberFactoryTemplate.class.getClassLoader())`, you create a new class loader using the default class loading strategy. At runtime, packages are only equal if they are defined by the same class loader such that the created class's package differs from the one of the redefined class.

To avoid this, you need to inject the class into the package of the loader of the anonymous class. You can use the `INJECTION` default strategy or, starting with Java 9, you can use a strategy using a method handle lookup to avoid the use of unsafe API.

**Comment by adamjryan** [comment]
Thanks for the speedy response. I added the ClassLoadingStrategy.Default.INJECTION and now get:
`Exception in thread "main" java.lang.NoSuchMethodError: Scenario$NumberFactoryTemplate$1.<init>(LNewNumberFactory;)V`
I'm still a bit unclear on the cause of the issue as if the class is being cloned it shouldn't need access to anything from the original class, although I can see the need to link it with the package of the common interface.

**Comment by raphw** [comment]
The problem is that the original class defines an anonymous inner class. This class captures its defining class implicitly, if you look at the anonymous class's class file, you will see that it declares a constructor that takes `NumberFactoryTemplate` as an argument.

By replicating the original class, you do not change the anonymous inner class. You would need to define a similar class and use `MemberSubstitution` to replace the constructor call. This is however a bit of work and difficult to automate. Ideally, you refactor the code to avoid the anonymous inner class.

**Comment by adamjryan** [comment]
Ah the goal was to generate a new inner class as well, I'll take a look at MemberSubstitution. Thanks.
