### ISSUE TITLE
Support Attach on IBM J9

### ISSUE THREAD

**Issue by CodingFabian** [raphw/byte-buddy#55]
The J9 from IBM also has attach functionality,
it can be used the same way as the sun/oracle functionality, but it does not require the tools.jar and it is named differently,
check for example this attach from openjpa https://github.com/apache/openjpa/blob/trunk/openjpa-kernel/src/main/java/org/apache/openjpa/enhance/InstrumentationFactory.java
simply use "com.ibm.tools.attach.VirtualMachine"

**Comment by raphw** [comment]
I researched this a bit and this is not J9 specific. As a matter of fact, J9 did it right in the first place as it returned the JRE location from `java.home` while OpenJDK returned the installation folder (different for JRE and JDK installations). However, both VMs are now supported. Additionally, the folder layout of the Macintosh build of the JVM is now supported.

Fixed in master.
