### ISSUE TITLE
MemberSubstitution stacksize not considered for custom Substitution implementations

### ISSUE THREAD

**Issue by quarante-2** [raphw/byte-buddy#554]
Hi Raph, I was expecting it to work similar to [this](https://github.com/raphw/byte-buddy/blob/ea6cc5a37394c9a34e62ac996feee19e542db102/byte-buddy-dep/src/main/java/net/bytebuddy/asm/MemberSubstitution.java#L1963).
Thanks!

**Comment by raphw** [comment]
Yes, you are right. The member substitution component is still "in the making". I just added the possibility recently and it is not yet fully feature complete. That I opened the API without fixing this issue was an oversight that I need to adress in a future release.

If this is important to you and you are using it in a commercial context, let me know if you want to sponsor the work; otherwise I hope to make this right some time this year or early next year.

**Comment by raphw** [comment]
This is fixed on master, could you test it as Byte Buddy is not making use of this feature itself yet? Would help to double-check. Thanks!

**Comment by quarante-2** [comment]
It's for a side project - so unfortunately I can't do it.
But I appreciate your work and look forward to improvements of the member substitution component.

Thanks a lot for the fix, all my tests passed!

**Comment by raphw** [comment]
Great, will be part of the next release! Thanks for reporting.
