### ISSUE TITLE
Skipping classes with unsupported bytecode versions

### ISSUE THREAD

**Issue by felixbarny** [raphw/byte-buddy#566]
I've got multiple reports where the application crashed because of instrumenting JDBC drivers which very old class file versions:
- https://discuss.elastic.co/t/java-lang-verifyerror-with-java-agent/156882
- https://github.com/elastic/apm-agent-java/issues/197

The problem mostly manifests itself with this exception: `java.lang.IllegalStateException: Cannot write type to constant pool for class file version Java 2`

But I also got a report for a `VerifyError` (see first link) which I could not reproduce, however.

Is there a way to just skip all classes with a class file version < 5? Ideally with a warning that the user has an unsupported library on the classpath. Or is there a way to catch and intercept the exception in byte buddys `ClassFileTransformer` and to return `null` from the `transform` method?

**Comment by raphw** [comment]
You can add a `TypeConstantAdjustment` visitor as your first visitor. This would fix this issue. Otherwise, you can add a raw matcher and read the class file version out of the byte array provided to it if you wanted to ignore classes of given versions. This is also where you could do the logging.

**Comment by felixbarny** [comment]
Great, thanks a lot for the tip!

**Comment by felixbarny** [comment]
> Otherwise, you can add a raw matcher and read the class file version out of the byte array provided to it if you wanted to ignore classes of given versions.

Not quite sure how that would work, as the `byte[]` is not provided in `net.bytebuddy.agent.builder.AgentBuilder.RawMatcher#matches`. What would be cool is if `TypeDescription` had a method `ClassFileVersion getClassFileVersion()` which would make this quite easy. Then there could even be a convenience `ElementMatcher` in `ElementMatchers`.

The `TypeConstantAdjustment` sounds great but I think just not messing with bytecode older than Java 5 seems to be safer. I could imagine that there are even some nasty bugs in such old javac compilers which might interfere with Byte Buddy.

**Comment by raphw** [comment]
You are right, I remember that I considered providing the argument. I think that I found that parsing all class files that walk through the transformer played out quite desastrous for performance which is why I hesitated but if you exclude enough classes it should just work.

I cannot really add the method as this would break with the abstraction between loaded and unloaded classes and it would require keeping a reference to the array what could cause massive leakage.

What you could do would be add an ASM visitor wrapper and to throw an exception (make sure to disable the stack trace capture, forth argument of the runtime exception constructor) when you discover the version in the visitor. This might sound expensive as you are using exceptions for control flow but it will still be much cheaper then parsing the byte array twice.

**Comment by felixbarny** [comment]
I'm sorry but I can't seem to find how I can add an AsmVisitorWrapper to an `AgentBuilder.Transformer.ForAdvice().advice`. I can see that it's possible with `AgentBuilder.Transformer.ForAdvice().transform`, however.

**Comment by raphw** [comment]
You can register multiple visitors on the `DynamicType.Builder` that is provided by the transformer. They are applied in registration order.

**Comment by felixbarny** [comment]
Implemented in https://github.com/elastic/apm-agent-java/pull/320

Thanks for your help!
