### ISSUE TITLE
[Java 11] Invalid automatic module name

### ISSUE THREAD

**Issue by mpe85** [raphw/byte-buddy#623]
When I put the byte-buddy library onto the module path in Java 11, the module name "byte.buddy" "is automatically generated from the library name "byte-buddy-1.9.10.jar".
The problem is that "byte" is a keyword and is therefore not allowed in module names. The compiler does not accept it. Renaming the library is not an option because the dependencies are automatically managed by the build system (in my case: gradle).
I saw there is a module-info.class present in META-INF/versions/9, but i guess this only works for Java 9 (?).
Could you please add module info to the library so that it also an be used as a module in Java 11?
Thanks!

**Comment by raphw** [comment]
The module-info.class should apply to all versions starting from Java 9 and older if class loaders adhere to the standard. I am however aware that there is an issue with the folder entries currently missing. I just updated the plugin that I use for generating the module-info to generate these entries.

Could you try building Byte Buddy but with setting the *modulemaker-maven-plugin* to version 1.7? Does it work for you then?

**Comment by raphw** [comment]
That said, using Byte Buddy 1.9.10, I have no problem loading the module-info.class that is included in the jar file.

What is your setup that displays this behavior?

**Comment by mpe85** [comment]
I messed it up to set the module path correctly in Gradle. Now I am able to compile my stuff. Sorry for that, it was my mistake.
But there's still another problem: I'm using eclipse 4.10 and it does not recognize the module-info.class inside META-INF/versions/9 thus displays an error saying 'net.bytebuddy' cannot be resolved to a module. If I repackage the jar and put module-info.class in the top-level directory, it gets recognized by eclipse and everything's fine. I guess eclipse does not (yet?) handle multi-release jars correctly. Are you aware of that? What IDE do you use?

**Comment by raphw** [comment]
I had a case reported that OSGi-based applications require a folder structure present in the jar to discover any entries within these folders. Since Byte Buddy is Java 5 compatible, I am injecting a module-info.class using a tool that does not create this folder structure which I have now fixed in the tool. With Eclipse being based on OSGi, you might just discover this problem.

Therefore, I was wondering if you could try Byte Buddy with the updated plugin. For this, you only need to build Byte Buddy and try out the snapshot-version to see if the module-info.class is discovered correctly this time.

In any way, this is to be considered a bug in Eclipse as the JVM is capable of discovering the module-info.class even without the folders present.

**Comment by mpe85** [comment]
I tried it with a 1.9.11 snapshot build as you suggested and eclipse discovers the module info correctly now.

**Comment by raphw** [comment]
Great, thanks, I will release a new version in the next days.
