### ISSUE TITLE
Question:  Getting the starting line number of method being modified.

### ISSUE THREAD

**Issue by tylerbenson** [raphw/byte-buddy#645]
When using `@Advice.OnMethodEnter` is there an easy and performant way to get the line number of the method being modified?  I would like to be able to include this information in my instrumentation.  (Obviously this is assuming that line numbers are included in the compiled class files and not disabled.)

If Byte Buddy doesn't expose this somehow, how would I do it with ASM?

Thanks!

PS.  I see your response in #283, but am hoping maybe there is a new development?

**Comment by raphw** [comment]
There is no good performant way of doing this but you can create a `new Throwable()` and get the first frame which will include the line number. Since Java 9, you can use the `StackWalker` API to get hold of this information in a much more performant manner.

Byte Buddy does not include this information as it is only available while processing the method what Byte Buddy does on the fly to avoid a reiteration. It might neither be available. You can of course write a custom `MethodVisitor` to extract it.

**Comment by raphw** [comment]
Please reopen this ticket if you have any further questions.

**Comment by wyzssw** [comment]
@raphw  why not use org.objectweb.asm.MethodVisitor#visitLineNumber to get lineNumber?

**Comment by raphw** [comment]
It only refers to a label and can be timed in different ways. For a one-pass instrumentation, this creates a row of issues.
