### ISSUE TITLE
Slow subclassing of class with methods with Optional<T>

### ISSUE THREAD

**Issue by J-cztery** [raphw/byte-buddy#686]
1.9.12
VisualVM points towards : TypeDescription$Generic$LazyProjection$ForLoadedReturnType.resolve()
Here is the condensed reproducer... 
Looks like it is doing too much work when generating classes of the same parent. 
```
   public interface Gettable<T> {
        @NonNull Optional<T> get1();
        @NonNull Optional<T> get2();
        @NonNull Optional<T> get3();
    }
    public static class TestReproducer implements Gettable<Object>
    {
        public Object accept(Object obj) {
            return null;
        }
        @Override public Optional<Object> get1() {
            return null;
        }
        @Override public Optional<Object> get2() {
            return null;
        }
        @Override public Optional<Object> get3() {
            return null;
        }
    }

    @Test public void reproducer() throws Exception {
        int counter =0;
        ByteBuddy bb = new ByteBuddy();
        for (int i = 0; i < 1000000; i++) {
            TestReproducer rr = bb.subclass(TestReproducer.class)
              .name("zupa_buraczkowa" + i)
              .defineMethod("accept", Object.class, Modifier.PUBLIC)
              .withParameters(Arrays.asList(Object.class))
              .intercept(SuperMethodCall.INSTANCE)
              .make()
              .load(TestReproducer.class.getClassLoader())
              .getLoaded()
              .newInstance();
            if (rr.accept(null) == null && i < System.currentTimeMillis()) {
                counter++;
            }
        }
        System.out.println(counter);
    }
```

**Comment by raphw** [comment]
This is not unexpected. It is quite costly in the JVM to process a generic type description and in your case, Byte Buddy has to process a hierarchy with generic types to check if bridge methods need to be included.

Is this a real scenario? Code generation and class loading are already very costly operations, I hope this is not time critical for your application?

**Comment by J-cztery** [comment]
>This is not unexpected.

It is shocking to me. 

>Byte Buddy has to process a hierarchy with generic types to check if bridge methods need to be included.

I bet it has to. I am not sure it has to do this every time. The subclass did not change since the last call. 

>Is this a real scenario? 

Yes, we have thousands of "property classes" generated runtime which inherit from the same class but we want the actual property name in the call stack. They will all inherit from the same PropertyClass but all we want, really is to rename classes at runtime. 
It happens during the UI is loaded and i can't make it many times slower than CGLib implementation i am trying to replace.

**Comment by raphw** [comment]
You should reuse types that you have generated previously. You might want to wrap the generation in a `TypeCache`.

**Comment by J-cztery** [comment]
>You should reuse types that you have generated previously. You might want to wrap the generation in a TypeCache.

In the code above each generated class is different (has different name) and the whole point is it having different name. 
I agree, that things should be cached but it has to happen on the level that limits calls to `TypeDescription$Generic$LazyProjection$ForLoadedReturnType.resolve()`.Is there a way to do it ? 

I am already caching classes with the same name. During normal startup of application there is ~20000 calls to create a new named instance which results in 500 calls to ByteBuddy to actually generate class. This interaction with ByteBuddy is taking most of the time.
The sample code above is distilled minimal reproducer that shows the problem. Its only purpose is to narrow it down to make things easier for you if you wanted to fix it.
Is there a way to fix it ?

**Comment by raphw** [comment]
What you can do is to create the class once and then `redefine` and rename it. That way, Byte Buddy can do much less work if you tune the parameters, e.g. by setting an inactive `MethodGraph.Compiler` in the `ByteBuddy` instance you are using.

Byte Buddy has no chance of knowing what your usage pattern is and needs to recreate the class on every request if you do not express this requirement explicitly.

**Comment by rowanworth** [comment]
Hi Rafael! FYI I work with @J-cztery, and just to clarify the goal here we're using generated classes for the sole purpose of annotating stack traces to assist in debugging -- the dynamic class names we create include information about the operation in progress. I appreciate this is perhaps not a compelling use case for such a rich code generation library, and we're mainly here because ByteBuddy is generally recommended as a migration pathway from cglib which we're looking to replace.

Anyway, thanks for your pointers so far. With some effort I've gotten the runtime of the reproducer test down considerably, and I'd like to document the process because (a) there's a loooot of different configuration options and cacheable work and it wasn't easy to find documentation about how everything fits together and (b) it gets very complex and I'm curious if I'm missing a simpler way to do things.

I started with a slightly cutdown version (which removes instantiation of the dynamic type to focus on class generation alone):

```
    @Test public void reproducer() throws Exception {
        int counter =0;
        long start = System.currentTimeMillis();
        ByteBuddy bb = new ByteBuddy();
        for (int i = 0; i < 5000; i++) {
            Loaded<TestReproducer> loaded = bb.subclass(TestReproducer.class)
                    .name("zupa_buraczkowa" + i)
                    .defineMethod("accept", Object.class, Modifier.PUBLIC)
                    .withParameters(Arrays.asList(Object.class))
                    .intercept(SuperMethodCall.INSTANCE)
                    .make()
                    .load(TestReproducer.class.getClassLoader());
            Class<? extends TestReproducer> clazz = loaded.getLoaded();
            counter++;
        }
        System.out.println(counter + " in " + (System.currentTimeMillis() - start) + "ms");
        // 5000 in 5234ms
    }
```

First step was to take the `Loaded` instance out of the loop, and `redefine()` it at each iteration. The loop is now:

```
            Builder b = bb.redefine(loaded.getTypeDescriptionI haven't tried it in anger but a 1.5x slowdown on this codepath is probably acceptable for us. Maybe it would have made more sense for us to go directly to the net.bytebuddy.jar.asm package to generate these classes but I'm out of time to investigate that tangent.(), new ClassFileLocator() {
                @Override public Resolution locate(String s) throws IOException {
                    return new Resolution.Explicit(loaded.getBytes());
                }

                @Override public void close() throws IOException {

                }
            }).name("zupa_buraczkowa" + i);
            Class<? extends TestReproducer> clazz = b.make().load(TestReproducer.class.getClassLoader()).getLoaded();
```

And we're down to 4775ms, not bad. Next was to compute a MethodGraphCompiler up-front based on the initial generated class:

```
        /* init code */
        MethodGraph.Linked graph = MethodGraph.Compiler.ForDeclaredMethods.INSTANCE.compile(loaded.getTypeDescription());
        MethodGraph.Compiler methodGraphCompiler = new MethodGraph.Compiler() {
            @Override public Linked compile(TypeDescription typeDescription) {
                return compile(null, typeDescription);I haven't tried it in anger but a 1.5x slowdown on this codepath is probably acceptable for us. Maybe it would have made more sense for us to go directly to the net.bytebuddy.jar.asm package to generate these classes but I'm out of time to investigate that tangent.
            }

            @Override public Linked compile(TypeDefinition typeDefinition, TypeDescription typeDescription) {
                return graph;
            }
        };
```

And use `bb.with(methodGraphCompiler)` in the loop. Runtime drops to 3731ms.

Adding `.with(TypeValidation.DISABLED)` gets us to 3415ms.

Profiling revealed most of the time at this point was going to `File.exists` on behalf of `ClassLoader.findLoadedClass` -- switching to "lookup" ClassLoadingStrategy bypassed that:

```
        /* init code */
        Class<?> methodHandles = Class.forName("java.lang.invoke.MethodHandles");
        Object lookup = methodHandles.getMethod("lookup").invoke(null);
        Method privateLookupIn = methodHandles.getMethod("privateLookupIn",
                Class.class,
                Class.forName("java.lang.invoke.MethodHandles$Lookup"));
        Object privateLookup = privateLookupIn.invoke(null, TestReproducer.class, lookup);
        ClassLoadingStrategy loadingStrategy = ClassLoadingStrategy.UsingLookup.of(privateLookup);

            /* within loop */
            Class<? extends TestReproducer> clazz = b.make().load(TestReproducer.class.getClassLoader(), loadingStrategy).getLoaded();
```

Down to 1440ms at this point, which is about as good as it got. I experimented with throwing a `TypePool` and `TypePool.CacheProvider` in and shaved off maybe 80ms. Profiling points mainly at iterating over methods and such within `MethodRegistry$Default.prepare()` on behalf of `RedefinitionDynamicTypeBuilder.make()`, which is not something I can pre-compute without bypassing pretty significant sections of the API so I stopped.

For reference, a cglib `AbstractClassGenerator` implementation with no pre-comptutation that emits a `super()` invocation for each of `TestReproducer`'s methods completes in ~900ms, but that's not a fair comparison because cglib is also creating an instance of each dynamic class. Adding that back into the ByteBuddy demo and we're up at ~1600ms.

I haven't tried it in anger but a 1.5x slowdown on this codepath is probably acceptable for us, assuming the discrepancy doesn't get worse for larger interface/class definitions. Maybe it would have made more sense for us to go directly to the net.bytebuddy.jar.asm package to generate these classes but I'm out of time to investigate that tangent, and intuitively it seems like there should be a high-level way to say "just rename this thingy that we already computed." `InstrumentedType.WithFlexibleName` seems tantalising from that perspective, but I was unable to make use of it in a performant way.

**Comment by raphw** [comment]
Thanks for the detailed summary. Yes, Byte Buddy tends to be a bit slower then cglib as it is doing a lot more work. You can try setting `-Dnet.bytebuddy.raw=true` and see what it gives you. Note that this can yield strange results when instrumenting generic types such as yours but it should not matter to the executing JVM.

If performance is a prime focus, I would otherwise always recommend to use vanilla ASM with as much precomputed information as possible.

**Comment by rowanworth** [comment]
Cool, `-Dnet.bytebuddy.raw=true` shaves another 100ms off.

Based on your vanilla ASM recommendation I also made time to experiment with a minimal ClassWriter implementation and the benchmark completes in ~350ms -- this is hardcoded for the specific hierarchy so not a fair comparison at all, but it gives an idea of the overheads implied by the cglib/ByteBuddy helpers.

Thanks for the pointers!

**Comment by raphw** [comment]
Great, I do not think that I can beat cglib but this is also due to the library taking some shortcuts that yield bugs which, if fixed, would probably decrease their speed similarly. The class file format is unfortunately quite complex and Byte Buddy tries to take care of all edge cases.

Please reopen this ticket if you have further questions.
