### ISSUE TITLE
Performance of Advice.Origin with type Method

### ISSUE THREAD

**Issue by carterkozak** [raphw/byte-buddy#714]
Using `Advice` to request the `Method` results in significantly slower performance than using a dynamic proxy.

```java
@Advice.OnMethodEnter
public static void enter(@Advice.Origin Method method) {
   log.info("Method: {}", method);
}
```
results in bytecode corresponding to:
```java
DemoAdvice.enter(TestInterface.class.getMethod("testMethod", String.class, Integer.TYPE));
```

Executing `Class.getMethod(String, Class<?>[])` for every invocation increases runtime of instrumented methods from 15ns/op to 140ns/op on java 8.

**Comment by raphw** [comment]
This is the default behavior to avoid adding a field what makes the advice unapplicable for retransforming classes what is its primary use case. If you are using `MethodDelegation`, the method instance is cached by default since delegation typically alters the instrumented class.

What makes you use advice for this? It would be trivial to add as an opt-in behavior.

**Comment by raphw** [comment]
For creating proxies, using `MethodDelegation` is typically the best alternative. `Advice` inlines code what requires additional I/O compared to method delegation whereas delegation is rather cost-efficient if you keep your reference of `MethodDelegation.to(...)`. The advantage of advice is rather being class loader agnostic what is mostly useful when writing Java agents.

You probably want to reuse existing types, too instead of regenerating them on every call. Have a look at `TypeCache` for this.

**Comment by carterkozak** [comment]
Hi @raphw, sorry for delayed response. Unfortunately in my use case (emulating dyanamic proxies for more performant instrumentation without adding as many stack frames) I haven't been able to produce the same behavior using SuperCall without additional stack frames for instrumentation. It's possible that I've misunderstood how a piece works and done something incorrectly.
If you could point me in the right direction I'd be happy to take a look at implementing the optimization you described to cache the method object.

**Comment by raphw** [comment]
That is right, you will always have additional stack frames for delegation. If you want to avoid performance overhead with advice, maybe create a string-typed origin and pass it to a cache later where you look up a previously created `Method` instance based on the string key to avoid recreating it.
