### ISSUE TITLE
DiscoveryStrategy and performance

### ISSUE THREAD

**Issue by bsideup** [raphw/byte-buddy#715]
in [my agent](https://github.com/reactor/BlockHound), the instrumentation time jumps from ~600ms to 1s and higher if I use `DiscoveryStrategy.SinglePass` instead of `DiscoveryStrategy.Explicit`.

The instrumentation consists of 2 raw type matches that match to the same result as I would use in my `Explicit` list filtering.

Since `SinglePass` discovery reads the same source (`instrumentation.getAllLoadedClasses()`), I wonder from where the overhead comes from and if there is anything to disable to make it faster?

Thanks in advance!

**Comment by raphw** [comment]
I assume this is due to the `LinkedHashSet` filtering in the strategies constructor. This is to avoid duplicates as users might supply classes twice (by accident). This would have unforseeable effects and must therefore be avoided. If you can guarantee more features to your iteration, I would assume that the best and most performant approach would be to implement the strategy yourself. For example, the `getAllLoadedClasses` array does not contain duplicates and you do not need the set filtering for this reason.

**Comment by raphw** [comment]
Closing this as there is no specific goal.
