### ISSUE TITLE
Excluding asm-tree prevents usage of JSRInlinerAdapter

### ISSUE THREAD

**Issue by CodingFabian** [raphw/byte-buddy#74]
The exclusion of asm-tree prevents usage of a couple of commons classes, in my case JSRInlinerAdapter.
Not sure if you want to remove the exclusion, or document that case

**Comment by raphw** [comment]
If you want to use ASM directly, you should repackage Byte Buddy dep into your own namespace. Otherwise, compatibility cannot be guaranteed as the ASM namespace defines many different versions that are incompatible to one another.

For further reference, have a look at the ASM FAQ where this is recommended and the Byte Buddy readme that discusses the issue.
