### ISSUE TITLE
Allow creation of multiple method delegations to the same instance

### ISSUE THREAD

**Issue by klaasb** [raphw/byte-buddy#76]
When one tries to generate more than one method delegation to the same instance, Byte Buddy will try to add the same static field twice and fail.

I would expect it to just re-use the field that's already there and guaranteed to have the correct instance assigned.

The workaround currently is to specify the field name and just generate two different fields with the same value, or generate the field and delegation myself, which isn't that hard either.

**Comment by raphw** [comment]
Ifyour delegators are equal, this is exactly what is happening. I guess that you have some additional configuration like a filter? Let me look into it and see if I can remodel this solution.

**Comment by klaasb** [comment]
You're right about the filter, though can a filter actually change the contents of the generated static field?
Sorry for not providing example code, mine looks roughly like this:
```java
...
.defineMethod(getSomething)
.intercept(
    MethodDelegation.to(delegate, Delegate.class, "getSomethingDelegate")
        .filter(ElementMatchers.named("getSomething"))
.defineMethod(getSomethingElse)
.intercept(
    MethodDelegation.to(delegate, Delegate.class, "getSomethingElseDelegate")
        .filter(ElementMatchers.named("getSomethingElse"))
```
There might be other ways to do this with Byte Buddy's API, that was the first I discovered.

**Comment by raphw** [comment]
The wait it is thought of is that you would append an `AmbigouityResolver` that figures out what method to bind in each case but I understand why this is not great. 

```java
.defineMethod(getSomething)
.intercept(
    MethodDelegation.to(delegate, Delegate.class).withAmbiguityResolver(myResolver)
.defineMethod(getSomethingElse)
.intercept(
    MethodDelegation.to(delegate, Delegate.class).withAmbiguityResolver(myResolver)
```

As long as the resolver implements the correct `hashCode`, `equals` contracts, Byte Buddy figures out that the implementations are identical and therefore compatible.

The problem is that there is currently no way for two `Implementation` instances to negotiate a common definition state for an instance. This would require to detach the preparation logic what would be a significant change in the application's architecture and the public API. The best Byte Buddy can do is to trivially merge implementations if they are equal and throw an exception if they register conflicting state. I will keep this in the back of my head but for now I can unfortunately not offer a solution.
