### ISSUE TITLE
Support a MethodVisitor in a Transformer

### ISSUE THREAD

**Issue by CodingFabian** [raphw/byte-buddy#77]
Right now, a builder supports only a classVisitor:

```
new Transformer() {
  @Override
  public Builder<?> transform(Builder<?> builder, final TypeDescription typeDescription) {
    return builder.classVisitor(new ClassVisitorWrapper() {
```

This way one can use bytebuddy for type matching, but implement method logic using asm.

if I now only want to target a specific method, I would need to check it the ASM way:
```
MethodVisitor mv = super.visitMethod(access, methodName, desc, signature, exceptions);
                    if (!methodName.startsWith("foo")) {
                      return mv;
                    }
                    if ((Opcodes.ACC_PUBLIC & access) == 0) {
                      // skipping non public methods
                      return mv;
                    }
```

It would be great if I could specify the method matching logic using a bytebuddy matcher, and then only fall back to my custom visitor.

a proposed api could look like
```
          public Builder<?> transform(Builder<?> builder, final TypeDescription typeDescription) {
            builder.method(methodMatcher).methodVisitor(new MethodVisitor() {
```

and then the given MethodVisitorSubclass would be what is used after a method is found matching.

**Comment by raphw** [comment]
I am going to include this in the currently planned revision of the public API which will also allow for definition of generic types. The idea is, that this form of interception allows for a simple decoration of existing methods without rebasing / redefining them, i.e. that the `MethodVisitor`s become stackable. The same will go for adding annotions without changing an existing method what is another feature that was requested.

So to speak, it will take a little bit to include this as I need to rework the internal representations of types before taking on the API refactorizatization. But it will become a part of the API, so much I can say.

**Comment by CodingFabian** [comment]
awesome. This adds to the versatility of bytebuddy!

**Comment by raphw** [comment]
I choose a different part for addressing this use case.

I believe that using ASM visitors is mainly desireable for users that want to redefine classes. In this case, a user only wants to change declared methods. For the general use case, it is already possible to use `MethodVisitor`s implementing a custom `Implementation`.

Therefore, I tweaked the existing API for `ClassVisitorWrapper`s a bit and added convenience visitors for `ForDeclaredMethod` and `ForDeclaredField`. This gives a big advantage that these visitors only require discovering declared methods instead of parsing the entire method inheritance tree for a given type (i.e. allows for using `ByteBuddy` with a precomputed `MethodGraph.Empty` to speed up the instrumentation process).

The new API can be used as follows:

```java
new AsmVisitorWrapper.ForDeclaredField()
    .match(someFieldMatcher(), bew FieldVisitorWrapper() { ... })
    .match(someOtherFieldMatcher(), bew FieldVisitorWrapper() { ... })

new AsmVisitorWrapper.ForDeclaredMethod()
    .match(someMethodMatcher(), bew MethodVisitorWrapper() { ... })
    .match(someOtherFieldMatcher(), bew MethodVisitorWrapper() { ... })
```

The matchers are cummulative, i.e. if two matchers match the same field, both wrappers are applied. The field and method visitor wrappers are functional interfaces to ease their use with Java 8.

This API will be part of Byte Buddy 0.8 which is planned for release some time this month.

**Comment by CodingFabian** [comment]
cool, I saw the changes, but it was hard for me to figure out how you supposed it to be used.

So I would do
```
new Transformer() {
  @Override
  public Builder<?> transform(Builder<?> builder, final TypeDescription typeDescription) {
    return builder.visitor(new AsmVisitorWrapper.ForDeclaredMethod().match(ElementMatchers.nameStartsWith("foo")), new MethodVisitorWrapper() { //do the asm advice }));
 }
...
```

**Comment by raphw** [comment]
Exactly like you wrote it. I will write some unit tests that demonstrate this and also update the documentation what hopefully makes it clearer.
