### ISSUE TITLE
Provide a source release without bundling gradle jars

### ISSUE THREAD

**Issue by mkoncek** [raphw/byte-buddy#778]
I would like to ask you that whenever you make a new release, you would also provide a .tar.gz, which does not contain ~120 MB of bundled gradle jars located in zips in "byte-buddy-gradle-plugin/gradle". As a package maintainer, it would save me some additional stripping work.
Thank you.

**Comment by raphw** [comment]
Hi, I will look into it. I am bundling Gradle jars since JDK 6 does no longer allow for downloading them due to outdated support for TLS.

**Comment by raphw** [comment]
I am afraid that the build complexity is already at its peak. I currently support Java 5 to 17 on Mac, Windows and Linux with both 32 bit and 64 bit. Therefore, I need to retain the current structure, also since older versions do not support TLS versions what makes downloads impossible and requires bundling.
