### ISSUE TITLE
@Origin for rebased class

### ISSUE THREAD

**Issue by Spikhalskiy** [raphw/byte-buddy#78]
Hi,

I make something like
```
public class InterceptorsInitializer {
    //This code should be executed before any usage/loading of MyObject class
    public static void registerModificationInterception() {
        TypePool typePool = TypePool.Default.ofClassPath();
        new ByteBuddy()
                .rebase(typePool.describe("MyObject").resolve(), ClassFileLocator.ForClassLoader.ofClassPath())            
                .method(named("modify")).intercept(MethodDelegation.to(typePool.describe("Interceptors").resolve()))
                .make()
                .load(InterceptorsInitializer.class.getClassLoader(), ClassLoadingStrategy.Default.INJECTION);
    }
}

public class Interceptors {
    public static void modify(@This MyObject myObject, @Origin Method method, String newState) {
        System.out.println(method);
    }
}
```

And get output "public final void MyObject.modify(java.lang.String)"
Instead of getting "public final void MyObject.modify$original(java.lang.String)" as I expected with `@Origin`.

If try to invoke this method in Interceptors#modify - instrumented version will called instead of original with endless recursion as a result.

Looks like a bug for me. WDYT? If you confirm that it should works as I expected - I will localize problem and prepare test.

**Comment by raphw** [comment]
This is expected behaviour. Origin returs a reference to the method that was matched. Reflection is not a good way to invoke original code. Theis code could for example be defined by a super class which is not accessibleto reflection.

Look into the @SuperCall and @Morph annotations instead.

**Comment by Spikhalskiy** [comment]
Hm... but... yes :) By tutorial origin returns link to original method, that was matched and instrumented, but not to the new instrumented version, that was used to replace the original one, so in case of rebased class it should be a method that was rebased and shadowed by some generated name like methodName$original.

Ok, thanks for advice, I will take a look at SuperCall and Morph to get reference to original method and invoke it.

**Comment by Spikhalskiy** [comment]
`@SuperCall` and `@Morph` can be used to invoke original method on the same entity. But I need to call original method of another entity of the same instrumented class. And it's not clear how to get this method reference for invocation in any form when @Origin actually pass not origin information.

**Comment by raphw** [comment]
Do I understand you correctly that you are trying to delegate from a proxy class to another proxy class? The `@Origin` annotation is built such that you can invoke an unproxied instance from a proxied instance. If you rebase a class such that you use a class either as a proxy or not, I would recommend you to add a `boolean` field to the class which activates or deactivates a proxy mode for instances of a class. If a class is not proxied, you can simply invoke the super method from the delegator.

**Comment by Spikhalskiy** [comment]
> Do I understand you correctly that you are trying to delegate from a proxy class to another proxy class?
Yes, you are right.

> The @Origin annotation is built such that you can invoke an unproxied instance from a proxied instance.
So... it's useless annotation for rebased class in that case?

> If you rebase a class such that you use a class either as a proxy or not, I would recommend you to add a boolean field to the class which activates or deactivates a proxy mode for instances of a class. If a class is not proxied, you can simply invoke the super method from the delegator.

Hm, it's a type of solution, but I want this another proxy instance to still be a proxy on this time for another code. I want to invoke original version only from my interceptor.

Looks like... a feature request? Because I can do it even with cglib by MethodInterceptor#intercept(arg0, arg1, arg2, **MethodProxy**)

**Comment by raphw** [comment]
You are right that this is not (currently) possible what you are trying to do. To begin with, the `@Origin` annotation is mainly used to explore the context of a method invocation. The annotation is mainly used for retreiving information about the method being intercepted, for example for doing reflection, e.g. accessing annotations (where it does not make sense to read the rebased method which is not annotated). Also, it can be used to make a *genuine* call to another instance.

Furthermore, it is more of an implementation detail that a method is rebased for a given interception. For example, if a method is *overridden* and not rebased, no such method exists and Byte Buddy would need to fall back to exposing a reference to the now overridden method. Using such a reference, it is not possible to invoke another instance's super method.

I am wondering what you are trying to achieve? Are you proxing another instance using another instance of the rebased class? Or are you chaining instances in some way? I wonder why you do not simply use the original instance (with the rebased class) as a proxy.

**Comment by Spikhalskiy** [comment]
I just found this question https://stackoverflow.com/questions/33842614/is-it-possible-to-redirect-a-method-call-to-another-instance-of-the-same-object and found it good example to start playing with ByteBuddy after your recommendation in one of my question on stackoverflow. So, I just take a look at tutorial. I have not stuck in it in any way because I need it for production (if I stucked I would use CGLib because I can do it easily with CGLib).

What I try to do - I want to rebase MyObject from this question and intercept modify() method to delegate it to original modify() method of another instance of MyObject, without call of instrumented version ("active" instance in context of this question).

In general - this stackoverflow question is awful and it's definitely not normal live situation. But getting descriptor of overridden method is definitely normal thing that such library should support. If library don't expose way to get overridden method reference - how should I do that? Manual code with loop by getDeclaredMethods to find <methodName>$original$randomThing(<same parameters>) :)

So... I think I don't need an advice how to do this right now in ByteBuddy. I believe there is another way how to do this. At least I can implement instrumented modify method of target entity to avoid recursion based on some flags. Or I can expose a new method of MyObject, which will call this original method maybe and call this new method as a delegator to avoid recursion. But I think I'm talking about very legal think - get meta information of replaced/overridden method. So, I suggest to convert this into feature request and maybe discuss how it can be implemented. Maybe I could spend some time to take into ByteBuddy's internals and prepare a pull request if design is clear for me.

**Comment by raphw** [comment]
Well, the problem would be that if the `modify` method was defined in a superclass of `MyObject`, this method would no longer be invokable using reflection. That is why I mentioned that the reflection API should only be used for *genuine* method calls. It should not matter for the behavior of a delegation if a method is rebased or defined by a super class, this is why the synthetic delegator method is not exposed. The rebasement process is an implementation detail that should not surface. There is no defined process or mapping constraint where the *original method* of an interceotion would be registered which is why your suggestion to add a utlity method would not work. Even worse, the interceptor is not aware of a rebasement itself; this is what makes it possible to subclass or rebase a class using the same API and expecting the same outcome.

My argument is that in your case, you have to adapt in your code that you want to use different instances of the same class in different ways. I would therefore suggest you to do something like the following:

1. Change your interceptor to read a field that is stored in the instance level (e.g. `Dispatcher`).
2. Run the interception only if this field is set, call the original code otherwise.
```java
public class Interceptors {
    public static void modify(@This MyObject myObject, 
                              @Origin Method method, 
                              @SuperCall Runnable runnable,
                              String newState,
                              @Field("dispatcher") Dispatcher dispatcher) {
     if (dispatcher != null) {
       dispatcher.dispatch(myObject, method, newState);
       // Can print: System.out.println(method);
     } else {
         runnable.run();
     }
    }
}
```
3. Now, to activate "interception mode", you simply need to set the `Dispatcher` field that you defined for the instance. (You can make this type-safe by impementing a setter interface):
```java
public interface Dispatchable {
  void setDispatcher(Dispatcher dispatcher);
}
```

This is what I would suggest.

**Comment by Spikhalskiy** [comment]
Yep, you recommendation is completely legal and it's a way to solve this specific question.
On the other question - looks like only reasons to don't expose new annotation like @RebasedMethod is 1) rebase/subclass/redefine should be transparent to interceptor
2) we now doesn't register that this $original method is origin for this instrumented method.

Could we make an exception and add such rebase-only annotation and think about implementation details or you don't want to include annotation specific only to one of rebase/subclass/redefine process?

**Comment by raphw** [comment]
I would make such an exception, however, the way that Byte Buddy is build, no `Implementation` instance is allowed to know if it is triggered for a rebasement or subclass instrumentation. This is by design and I argue that the advantages outweigh the disadvantages.

I want to keep the way of rebasement an implementation detail as I consider to offer an `invokedynamic` based replacement in the future. Therefore, unfortunately, I do not want to allow for accessing the rebased methods.

I understand that breaking out from the constraint to not allow `Implementation`s to distinguish between interception type can be a limitation but I argue that there is always a better solution to this problem as the one I suggested in your case.

If I ever find a way to solve this problem in a better way, I will remember this discussion and try to implement your suggestion but for now I am afraid that it would bloat the code base and break Byte Buddy for future changes. But for now, I must unfortunately say that I do not want to support such a feature. Thank you however for your thoughts, I do very much understand your requirement.
