### ISSUE TITLE
[Gradle plugin] Make it possible to apply it on JAR tasks (e.g. shadowJar)

### ISSUE THREAD

**Issue by bsideup** [raphw/byte-buddy#785]
Hi!

We would like to run some post-processing after creating a shaded jar and wanted to use ByteBuddy for it.
But it seems that it only works with `AbstractCompile` tasks.

Could you please consider adding support for the [Jar task](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/bundling/Jar.html)?

Thank you!

**Comment by raphw** [comment]
I'll consider it. Not sure if it's feasible since shaded artifacts can be partial and I have no idea how to get hold of the class path from the `Jar` task. Do you know how this can be done?

As of today, you can always use `Plugin.Engine.Default` to implement your own transformation from Gradle. The Gradle plugin is only a convenient wrapper for it.

**Comment by raphw** [comment]
I rewrote the plugin completely. In the next release, Byte Buddy offers three tasks, the `ByteBuddyJarTask` can be used to transform classes in a class file.
