### ISSUE TITLE
Local Variable Table Access

### ISSUE THREAD

**Issue by jlogelin** [raphw/byte-buddy#818]
First off - thanks for an awesome library. Composing ASM natively is painful and slow - byte-buddy takes away 95% of that pain.

I have a scenario where it I would like to access all method local variables when an exception occurs. I love the pattern of annotated injections for `@AllArguments` and other context variables during instrumentation. Would it be possible to have a `@LocalVariables` Map that would inject the local variable table? (I think this is possible with native ASM. ) If not, what is the best way to go about this in byte-buddy?

```
@Advice.OnMethodExit(onThrowable = Throwable.class)
private static void exit(@Advice.LocalVariables Map<String, Object> locals, ...) {
  // This may not be the same as source without debug flags on, but thats ok 
  Object var = locals.get("someVarName"); 
   ...
}
```

**Comment by raphw** [comment]
Glad you like the library, I appreciate it.

Local variables are a bit tricky to access reliably as it would require to keep track of their lifecycle throughout the method's body since blocks are not marked in byte code. With code obfuscators and alternative languages around, it would also be a rather unstable access path. As a matter of fact, even method arguments can expire before the end of the method and Byte Buddy needs to play a bunch of tricks to retain them in all contexts to avoid verification errors. Also, note that the local variable debug information is optional and might be missing for some methods; then you'd need to deduce type and livety

If you needed this functionality, you can program your own annotation binding. Have a look into the advice binding for `@Advice.Argument`. Local variables are just added at inidices after the method arguments and you could create an offset accessing annotation to read them if you control the code being run, but at your own risk of course.
