### ISSUE TITLE
'enableBootstrapInjection' no longer working in ByteBuddy Agent fluent API

### ISSUE THREAD

**Issue by kriegaex** [raphw/byte-buddy#854]
I found several issues mentioning `.enableBootstrapInjection(instrumentation, tempFolder)` or similar, e.g. #228, #577. The code snippets from there do not seem to work anymore. There is exactly one [reference to `enableBootstrapInjection`](https://github.com/raphw/byte-buddy/search?q=enableBootstrapInjection&unscoped_q=enableBootstrapInjection) in the whole repository and that line of code it is several years old according to Git Blame. No test references it, so there is no usage example.

If I want to write `AgentBuilder.Default().enableBootstrapInjection(instrumentation, tempFolder)` in my IDE, the method cannot be resolved. Is something broken there? Or has it been removed? Do I have to use it in another way? The ByteBuddy tutorial on the website methions that method, but does not explain any details. Without even an automatic test it is difficult so see how to use it for a beginner like me.

**Comment by kriegaex** [comment]
Okay, on GitHub I cannot search the commit history, locally I can of course. I think the answer could be 274a5f2 where in `AgentBuilder` you removed
* `AgentBuilder enableBootstrapInjection(Instrumentation, File)`,
* `AgentBuilder enableUnsafeBootstrapInjection()`,
* `AgentBuilder disableBootstrapInjection()`
in favour of `AgentBuilder with(InjectionStrategy)`. Maybe you should update the [tutorial](https://bytebuddy.net/#/tutorial`) and you also could add unit tests for bootstrap loader injection.

**Comment by raphw** [comment]
The tutorial is hopelessly outdated at this point and I really hope to find some time to redo it this year. You are right about the injection strategy, I made the entire injection mechanism pluggable, therefore the methods were changed.

Glad you found out about it.

**Comment by dipanzan** [comment]
Hi,

This is a stupid question, but I'm trying to attach an Agent to a another process using ByteBuddy.attach("agent.jar", "pid"). Now on IntelliJ under the same project, it successfully attaches to a different process. I'm assuming there's no problem here because they all fall under the same classloader.

But if it's a separate project, or a java app from the command line (java -jar), the said mechanism doesn't work anymore. It complains about my Agent ClassNotFoundException in thread **"Attach-Listener"**. After a few days of struggling with this, I came to the conclusion that I've to manually inject classes to the boot/system classloader in order to resolve this, but I'm not finding much success. Can you point me to any resources/tutorial where I can get an idea on how to achieve this?

Main goal: Attach an agent to change method (Enter/Exit) on any Java process running on the same by scanning PIDs.

**Comment by raphw** [comment]
You need to bundle all classes of your agent within a single "shaded" jar. There's the shade plugin for Maven and the shadow plugin for Gradle.

**Comment by dipanzan** [comment]
> You need to bundle all classes of your agent within a single "shaded" jar. There's the shade plugin for Maven and the shadow plugin for Gradle.

Hi,

First of all thank you for the prompt reply, and your library is awesome!

I'll definitely research on how to create a shaded jar. My current approach was as follows:
1 Create manifest with (Agent-Class, Can-Redefine-Classes, Can-Retransform-Classes)
2. Bundle manifest + jar (IntelliJ compiled Agent.class) programmatically using FileOutputStream (path to target classes/Agent.class) + ZipOutputStream => agent.jar
3. Scan the VM list using VirtualMachine.list() and get PID of any Java process to hook onto.
4. Supply said agent.jar and PID to ByteBuddy.attach().

Please forgive me for such an ignorant question (this is kind of advanced for me). Do I need to change the way I create my original agent.jar? The suggestion to create a shaded jar would I'm assuming have Advice classes (e.g TimerAdvice, measuring time elapsed of methods). The only extra class that I'm referencing are these auxiliary Advice classes inside my Agent class.

Lastly if you've the time (I completely understand if you are busy), why does the agent work when running from the same project, different main(), but fails to do the same thing when the other project is completely standalone. I'm really sorry again for all the barrage of questions, just trying to learn advance Java (I'm mostly a beginner/intermediate).

If I can get this to work, this will be a very big part of my MSc thesis, where I'm trying to measure software energy usage from the kernel, but need to hook onto any arbitrary function in a high level language without access to source code.

Thank you so much again!

**Comment by kriegaex** [comment]
Sorry, but I cannot resist replying. Please forgive me for being skeptical and maybe sounding a bit hostile:

1. Your question seems to be unrelated to this issue. Why are you hijacking it, instead of just asking a question on Stack Overflow with the _byte-buddy_ tag? You do not seem to want to raise a bug or enhancement request, but simply have a usage question. This is a bug/feature tracker.

2. I would be very interested in your MSc thesis or its description, because I have absolutely no idea what "measure software energy usage from the kernel" is supposed to mean or how you even want to start doing that and how instrumenting JVM code with Byte Buddy is supposed to help you there. If it is about how much time software spends in particular execution paths, why don't you attach a profiler like VisualVM to your running programs? You do not need BB for that.

**Comment by dipanzan** [comment]
> Sorry, but I cannot resist replying. Please forgive me for being skeptical and maybe sounding a bit hostile:
> 
> 1. Your question seems to be unrelated to this issue. Why are you hijacking it, instead of just asking a question on Stack Overflow with the _byte-buddy_ tag? You do not seem to want to raise a bug or enhancement request, but simply have a usage question. This is a bug/feature tracker.
> 2. I would be very interested in your MSc thesis or its description, because I have absolutely no idea what "measure software energy usage from the kernel" is supposed to mean or how you even want to start doing that and how instrumenting JVM code with Byte Buddy is supposed to help you there. If it is about how much time software spends in particular execution paths, why don't you attach a profiler like VisualVM to your running programs? You do not need BB for that.

I'm really sorry for using this platform for such a question. I was mainly interested in instrumenting a somewhat high level language and function/method executions. I didn't want to assume control over the source code, so ByteBuddy seemed like the perfect solution for such a use case (hooking onto any arbitrary function). From what I've gathered after using the BB API was that I needed to inject my Agent classes to the Boot/System classloader in order to achieve this, but the previous APIs were deprecated as you mentioned in the original post, hence I end up here.

Once again I'm really sorry, I'll delete my previous post and this one if it's against the rules.

**Comment by kriegaex** [comment]
I am not making the rules here, just sharing my opinion. I know that I was blunt, but I did not mean to insult you.

**Comment by raphw** [comment]
@dipanzan it's totally fine to ask a follow up question on an issue you assume is related, glad you found an answer. It's a lot to take in, so please ask away if there's more you wonder about.
