### ISSUE TITLE
Repository size is over 1 GiB

### ISSUE THREAD

**Issue by tkalmar** [raphw/byte-buddy#899]
While working on #897 i noticed that the repository is over one gigabyte in size (1.2 GiB).

The main contribution to  this size is the historical javadoc in the git history (about 600 megabyte)
After cleaning this repository size is down to 626 MB
The main offenders afterwards are:
```
9bf7b85f41cb   91MiB byte-buddy-gradle-plugin/gradle/6.0.1/gradle-6.0.1-bin.zip
cd80b2a86866   83MiB byte-buddy-gradle-plugin/gradle/5.4.1/gradle-5.4.1-bin.zip
3808b92eee31   82MiB byte-buddy-gradle-plugin/gradle/5.0/gradle-5.0-bin.zip
e69e8b723e35   69MiB byte-buddy-gradle-plugin/gradle/4.5/gradle-4.5-bin.zip
f04eb92f3f02   43MiB byte-buddy-gradle-plugin/gradle/2.14.1/gradle-2.14.1-bin.zip
86840a128200  7,7MiB .mvn/3.2.5/apache-maven-3.2.5-bin.zip
4853daddea2c  5,3MiB 1.8.15/index-all.html
4e2ec5b6f6b6  5,1MiB 1.4.18/index-all.html
66c7a6bbbc47  1,2MiB 1.8.15/net/bytebuddy/description/type/class-use/TypeDescription.html
```
This seems to be another round of old javadocs and gradle and maven versions

Is it necessary to keep these in git? It makes contributing unnecessary hard (long download over slow line) 
Perhaps it is possible to clean the git history for example with: https://rtyley.github.io/bfg-repo-cleaner/

**Comment by raphw** [comment]
I am not sure if I like the idea to rewrite history, generally, I recommend a shallow clone (depth 1) to avoid this.

The reason Gradle and Maven are included is that I am still building Byte Buddy on Java 5 and 6 where modern TLS is not supported such that the zip files cannot be downloaded due to missing HTTP offering. It would not be possible (or much harder at least) to support building with older JVMs on standard infrastructure otherwise.

**Comment by tkalmar** [comment]
Ok i understand your concerns about rewriting history, perhaps a warning for contributors should suffice...

**Comment by famod** [comment]
Do you still have to build on Java 5 and 6? I cloned the repo yesterday (for #1181) and was also very surprised by the size it.

**Comment by raphw** [comment]
Yes, I do. I recommed a shallow clone to avoid the size overhead.
