### ISSUE TITLE
Is it possible to attach bytebuddy to a different machine?

### ISSUE THREAD

**Issue by asasas234** [raphw/byte-buddy#902]
When I look at the API, they all only take the pid parameter, I understand there should be a place to set the target machine IP

**Comment by CodingFabian** [comment]
The whole Java attach API is limited to local machine for several reasons. Since the Java API does not allow this, ByteBuddy cannot provide it. Building a server process that you deploy on each machine and which then allows something like that via a custom protocol is doable, but outside the scope of ByteBuddy.

**Comment by raphw** [comment]
As Fabian said it. There is no mechanism built into the JVM for this. You'd need to deploy a Java program to the target matchine and attach from there.

**Comment by asasas234** [comment]
thanks @CodingFabian @raphw
